<?php
	/*
	Copyright (C) 2013  John F. Arroyave Gutiérrez
						unix4you2@gmail.com

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
	*/

	/*
		Title: Idioma espanol
		Ubicacion *[/inc/idioma/es.php]*.  Incluye la definicion de variables utilizadas para presentar mensajes en el idioma correspondiente
		NOTAS IMPORTANTES:
			* Por cuestiones de rendimiento se recomienda la definicion usando comillas simples.
			* Usar las dobles solo cuando se requieran variables o caracteres especiales.
			* Se pueden definir cadenas en funcion de otras definidas con anterioridad
			* Se puede hacer uso de notacion HTML dentro de las cadenas para dar formato
	*/

	// Cadena que describe el archivo de idioma para su escogencia
	$MULTILANG_DescripcionIdioma='हिन्दी - Hindi (by GoogleTranslator)';

	//Lexico general (palabras y frases comunes a varios modulos)
	$MULTILANG_Accion='कार्य';
	$MULTILANG_Actualizacion='अपडेट';
	$MULTILANG_Actualizar='नवीनीकरण';
	$MULTILANG_Administre='प्रबंधित करें';
	$MULTILANG_Agregar='जोड़ें';
	$MULTILANG_Ambiente='वातावरण';
	$MULTILANG_Ambos='दोनों';
	$MULTILANG_Anonimo='गुमनाम';
	$MULTILANG_Anterior='पिछला';
	$MULTILANG_Apagado='बंद';
	$MULTILANG_Aplicacion='आवेदन';
    $MULTILANG_Aplicando='आवेदन करना';
    $MULTILANG_Archivo='फ़ाइल';
	$MULTILANG_Asistente='जादूगर';
	$MULTILANG_Atencion='ध्यान दें';
	$MULTILANG_Avanzado='विकसित';
	$MULTILANG_Ayuda='मदद';
	$MULTILANG_Basedatos='डाटा बेस';
	$MULTILANG_Basicos='मूल बातें';
    $MULTILANG_BarraHtas='टूलबार';
    $MULTILANG_Buscar='खोज';
	$MULTILANG_Campo='क्षेत्र';
	$MULTILANG_Cancelar='रद्द';
	$MULTILANG_Capturar='कैद';
	$MULTILANG_CaracteresCaptcha='कैप्चा के लिए पात्रों की संख्या?';
    $MULTILANG_Cargando='लोड हो रहा है';
    $MULTILANG_Cargar='अपलोड';
	$MULTILANG_Cerrar='बंद करे';
	$MULTILANG_CerrarSesion='लॉग आउट';
	$MULTILANG_Cliente='ग्राहक';
	$MULTILANG_CodigoBarras='बार कोड';
	$MULTILANG_Columna='स्तंभ';
	$MULTILANG_Comando='कमांडो';
	$MULTILANG_ConfiguracionGeneral='सामान्य सेटिंग्स';
	$MULTILANG_Configuracion='विन्यास';
	$MULTILANG_ConfiguracionVarias='कई विकल्पों का विन्यास';
	$MULTILANG_Confirma='क्या आप वाकई जारी रखना चाहते हैं?';
	$MULTILANG_Continuar='जारी रखें';
	$MULTILANG_Contrasena='पासवर्ड';
	$MULTILANG_Controlador='ड्राइवर';
    $MULTILANG_Copias='बैकअप';
	$MULTILANG_Correcto='सही';
	$MULTILANG_Correo='ईमेल';
	$MULTILANG_Creditos='के बारे में';
	$MULTILANG_Cualquiera='कोई';
	$MULTILANG_Defina='परिभाषित करें';
	$MULTILANG_Descargar='डाउनलोड';
    $MULTILANG_Deshabilitado='विकलांग';
	$MULTILANG_Desplazar='विस्थापित';
    $MULTILANG_Detalles='विवरण';
	$MULTILANG_Disene='डिज़ाइन';
	$MULTILANG_Editar='संपादित करें';
	$MULTILANG_Ejecutar='निष्पादित करें';
	$MULTILANG_Elementos='तत्वों';
	$MULTILANG_Eliminar='हटाना';
	$MULTILANG_Embebido='एम्बेड';
	$MULTILANG_Encabezados='हेडर';
	$MULTILANG_Encendido='पर';
	$MULTILANG_Error='त्रुटि';
    $MULTILANG_Escritorio='डेस्कटॉप';
	$MULTILANG_Estado='स्थिति';
	$MULTILANG_Etiqueta='लेबल';
    $MULTILANG_Explorar='अन्वेषण';
	$MULTILANG_Exportar='निर्यात';
	$MULTILANG_Fecha='तारीख';
	$MULTILANG_Finalizado='तैयार';
    $MULTILANG_Filtro='फ़िल्टर';
	$MULTILANG_Formularios='फार्म';
	$MULTILANG_Funciones='पूर्व प्राधिकृत कार्यों';
	$MULTILANG_FuncionesDes='सुरक्षा कारणों से, अपने कस्टम कार्य या मॉड्यूल को इस क्षेत्र में पूर्व अधिकृत किया जाना चाहिए। किसी भी चरित्र के द्वारा अलग कार्य या कार्यों में जोड़ें.';
	$MULTILANG_GeneradoPor='द्वारा संचालित';
	$MULTILANG_General='सामान्य';
	$MULTILANG_Grande='बड़े';
	$MULTILANG_Grafico='ग्राफिक';
	$MULTILANG_Guardar='सहेजें';
    $MULTILANG_Guardando='बचत';
	$MULTILANG_Habilitado='सक्षम किया';
	$MULTILANG_Habilitar='सक्षम करें';
    $MULTILANG_Historico='इतिहास';
	$MULTILANG_Hora='समय';
	$MULTILANG_Horizontal='परिदृश्य';
	$MULTILANG_IdiomaPredeterminado='डिफ़ॉल्ट भाषा';
	$MULTILANG_Imagen='चित्र';
	$MULTILANG_Importando='आयात';
	$MULTILANG_Importante='जरूरी';
	$MULTILANG_Importar='आयात';
	$MULTILANG_InfoAdicional='अतिरिक्त जानकारी';
	$MULTILANG_Informes='रिपोर्ट';
	$MULTILANG_Ingresar='साइन इन करें';
	$MULTILANG_Instante='तुरंत';
    $MULTILANG_Ir='जाना';
	$MULTILANG_IrEscritorio='मेरी मेज पर जाएं';
	$MULTILANG_Licencia='लाइसेंस';
	$MULTILANG_LlavePaso='महत्वपूर्ण संकेत';
	$MULTILANG_Maquina='मेज़बान';
	$MULTILANG_Matriz='मैट्रिक्स';
    $MULTILANG_Modulos='मॉड्यूल';
    $MULTILANG_Mostrando='दिखा रहा है';
	$MULTILANG_MotorBD='डेटाबेस इंजन';
	$MULTILANG_Ninguno='कोई नहीं';
	$MULTILANG_No='नहीं';
	$MULTILANG_Nombre='नाम';
	$MULTILANG_NombreRAD='रेड नाम';
    $MULTILANG_Objeto='वस्तु';
    $MULTILANG_OlvideClave='मैं अपना पासवर्ड भूल गया';
	$MULTILANG_Opcional='ऐच्छिक';
    $MULTILANG_Opcion='विकल्प';
	$MULTILANG_OpcionesMenu='व्यंजना सूची';
	$MULTILANG_Otros='दूसरों';
	$MULTILANG_Pagina='पृष्ठ';
	$MULTILANG_ParamApp='आवेदन मापदंडों';
	$MULTILANG_Paso='चरण';
	$MULTILANG_Peso=' भार';
	$MULTILANG_Pequeno='छोटा';
    $MULTILANG_Pestana='टैब';
	$MULTILANG_Predeterminado='चूक';
    $MULTILANG_Previo='पिछला';
	$MULTILANG_Primero='पहले';
    $MULTILANG_Procesando='प्रसंस्करण';
    $MULTILANG_ProcesoFin='प्रक्रिया पूरी की';
	$MULTILANG_Puerto='बंदरगाह';
    $MULTILANG_Registrarme='साइन इन करें';
    $MULTILANG_Regresar='वापसी';
    $MULTILANG_Resultados='परिणाम';
	$MULTILANG_SaltarLinea='लाइन पर चलें';
    $MULTILANG_Si='हाँ';
    $MULTILANG_Siguiente='अगला';
	$MULTILANG_Seleccionar='का चयन करें';
    $MULTILANG_SeleccioneUno='एक का चयन';
    $MULTILANG_Servidor='सर्वर';
	$MULTILANG_Suspender='निलंबित';
	$MULTILANG_Tablas='टेबल्स';
	$MULTILANG_TablaDatos='डेटा तालिका';
	$MULTILANG_TiempoCarga='लोड होने का समय';
	$MULTILANG_Tipo='टाइप';
	$MULTILANG_TipoMotor='इंजन के प्रकार';
	$MULTILANG_Titulo='शीर्षक';
	$MULTILANG_TotalRegistros='कुल अभिलेख पाया';
	$MULTILANG_Ultimo='अंतिम';
    $MULTILANG_Usuario='उपयोगकर्ता';
	$MULTILANG_Vacio='खाली';
	$MULTILANG_Variables='चर';
	$MULTILANG_Version='संस्करण';
	$MULTILANG_Vertical='चित्र';
	$MULTILANG_ZonaHoraria='समय क्षेत्र';
	$MULTILANG_VistaImpresion='मुद्रक देखें';
	$MULTILANG_IDGABeacon='गूगल विश्लेषिकी आईडी';
	$MULTILANG_AyudaGABeacon='जो लोग चाहते हैं डेवलपर्स यहां अपने Google Analytics कक्ष से अद्वितीय पहचान डाल सकता है गूगल विश्लेषिकी का उपयोग कर अपने सॉफ्टवेयर के बारे में एक पूर्ण प्रवेश या वास्तविक समय आँकड़े है। Practico वास्तविक समय में सभी आंकड़े तू अपने Analytics पैनल भेज देंगे।';

	//Ventana de login
	$MULTILANG_TituloLogin='सिस्टम लॉगिन';
	$MULTILANG_CodigoSeguridad='सुरक्षा कोड';
	$MULTILANG_IngreseCodigoSeguridad='कोड दर्ज करें';
	$MULTILANG_AccesoExclusivo='इस सॉफ्टवेयर का उपयोग केवल पंजीकृत उपयोगकर्ताओं के लिए है। अपनी सुरक्षा के लिए, अपने यूज़रनेम और पासवर्ड का हिस्सा कभी नहीं।';
	$MULTILANG_LoginNoWSTit='प्रमाणीकरण वेब सेवा लोड करने की कोशिश में त्रुटि';
	$MULTILANG_LoginNoWSDes='The file_get_contents() function can not to load the XML output file built by Practico authentication process.<br>  Check your web server configuration/installation to see that this funtion can works correctly and without restrictions.<br>  A way to check that Practicos process is fine but your server doesnt allow to load the XML file<br>is opening the next link and checking if your browser loads the XML correctly.  Activating debug mode on your Practicos config you could see more details: ';
	$MULTILANG_OauthLogin='मेरे सामाजिक नेटवर्क का उपयोग कर लॉगिन';
	$MULTILANG_LoginClasico='Practicos खाते के साथ लॉगिन';
	$MULTILANG_LoginOauthDes='<b>सामाजिक नेटवर्क और अन्य प्रमाणीकरण प्रदाताओं</b><br>अपने पसंदीदा साइट से यूज़रनेम और पासवर्ड का उपयोग कर लॉगइन करने के लोगो पर क्लिक करें.';

	//Banderas de campos en formularios
	$MULTILANG_TitValorUnico='डुप्लिकेट को स्वीकार नहीं करता गई वैल्यू';
	$MULTILANG_DesValorUnico='पहले से ही प्रवेश की अनुमति नहीं किया जाएगा डेटाबेस में है कि मूल्य के साथ एक रिकॉर्ड है, अगर वहाँ प्रणाली है, इस क्षेत्र में दर्ज की गई जानकारी को मान्य होगा.';
	$MULTILANG_TitObligatorio='आवश्यक क्षेत्र';
	$MULTILANG_DesObligatorio='इस क्षेत्र अनिवार्य रूप में चिह्नित किया गया है। आप इस के लिए एक मान दर्ज नहीं करते हैं तो सिस्टम उपयोगकर्ता इनपुट रिकॉर्ड की दुकान नहीं करता है।';

	//Errores y avisos varios
	$MULTILANG_TituloInsExiste='ध्यान दें: स्थापना फ़ोल्डर सर्वर पर मौजूद';
	$MULTILANG_TextoInsExiste='इस संदेश को आप Practico की स्थापना के लिए प्रयोग किया जाता निर्देशिका को नष्ट नहीं है के रूप में सभी उपयोगकर्ताओं के लिए स्थायी रूप से दिखाई देता है। यह आप पहले से ही के लिए Practico के स्थापित एक पूरा कर लिया है, तो प्रक्रिया फिर से व्यापार <br> आप को महत्व की जानकारी के साथ विन्यास फाइल या डेटाबेस overwritting आरंभ फ़ोल्डर किसी भी बेनामी उपयोगकर्ता को रोकने के लिए एक अधिष्ठापन के अंत के बाद हटा दिया गया है कि आवश्यक है उत्पादन में प्रयोग आगे बढ़ने से पहले इस फ़ोल्डर को दूर करने के लिए महत्वपूर्ण है। आप इस फ़ोल्डर को नष्ट करना चाहते हैं तो आप अस्थायी या परीक्षण में नाम बदलने के लिए चुन सकते हैं। शब्दकोश हिन्दी यदि आप पहली बार इस स्क्रिप्ट चल रहा है और एक नया स्थापना करना चाहते हैं जब यह संदेश देख रहे हैं, तो आप विज़ार्ड शुरू कर सकते हैं  <a class="btn btn-primary btn-xs" href="javascript:document.location=\'ins\';"><i class="fa fa-rocket"></i> यहाँ पर क्लिक</a> ';
	$MULTILANG_ErrorTiempoEjecucion='रनटाइम त्रुटि';
	$MULTILANG_ErrorModulo='मुख्य मॉड्यूल में स्थित एक मॉड्यूल शामिल करने के लिए कोशिश कर रहा है <b>mod/</b> लेकिन Practico अपनी पहुँच बिंदु नहीं मिल सकता है।<br> मॉड्यूल स्थिति की जांच करें अपने व्यवस्थापक से परामर्श या इस संदेश से बचने के लिए परस्पर विरोधी मॉड्यूल को हटा दें।';
	$MULTILANG_ContacteAdmin='अपने सिस्टम व्यवस्थापक से संपर्क करें और इस पोस्ट की रिपोर्ट।';
	$MULTILANG_ReinicieWeb='आवश्यक सेटिंग्स बनाने के लिए और अपने वेब सेवा को पुनः प्रारंभ करें.';
	$MULTILANG_PHPSinSoporte='आपका पीएचपी स्थापना कोई समर्थन नहीं है प्रकट होता है';
	$MULTILANG_ErrExtension=' अक्षम लोगों के लापता या एक मॉड्यूल की आवश्यकता है PHP एक्सटेंशन';
	$MULTILANG_ErrLDAP=$MULTILANG_PHPSinSoporte.' LDAP समर्थन बाहरी प्रमाणीकरण पद्धति के रूप में उपयोग के लिए आवश्यक है।<br>'.$MULTILANG_ReinicieWeb.'.<br>व्यवस्थापक उपयोगकर्ता प्रमाणीकरण का उपयोग कर के नुकसान से बचने के लिए स्वतंत्र रहेगा.';
	$MULTILANG_ErrHASH=$MULTILANG_PHPSinSoporte.' हैश समर्थन की आवश्यकता है.<br>आप बाहरी प्रमाणीकरण अप इंजन पर पासवर्ड के लिए एक अलग एन्क्रिप्शन प्रकार चयनित अगर इस विस्तार की आवश्यकता है.<br>'.$MULTILANG_ReinicieWeb;
	$MULTILANG_ErrSESS=$MULTILANG_PHPSinSoporte.' सत्र समर्थन की आवश्यकता है. '.$MULTILANG_ReinicieWeb;
	$MULTILANG_ErrGD=$MULTILANG_PHPSinSoporte.' जी डी ग्राफिक्स पुस्तकालय की आवश्यकता है.<br>डेबियन उपयोग कर रहे हैं जो लोग, Ubuntu या उसके डेरिवेटिव एक कोशिश कर सकते हैं <b> apt-get install php5-gd </ b> to add it. RedHat or CentOS users <b> yum install php-gd </ b>. अन्य platfroms से उपयोगकर्ता अपने प्रलेखन Chech चाहिए.<br>'.$MULTILANG_ReinicieWeb;
	$MULTILANG_ErrCURL=$MULTILANG_PHPSinSoporte.' कर्ल पुस्तकालय की आवश्यकता है.<br>डेबियन उपयोग कर रहे हैं जो लोग, Ubuntu या उसके डेरिवेटिव एक कोशिश कर सकते हैं <b> apt-get install php5-gd </ b> इसे जोड़ने के लिए.<br>'.$MULTILANG_ReinicieWeb;
	$MULTILANG_ErrSimpleXML=$MULTILANG_PHPSinSoporte.' SimpleXML पुस्तकालय की आवश्यकता है.<br>'.$MULTILANG_ReinicieWeb;
	$MULTILANG_ErrPDO=$MULTILANG_PHPSinSoporte.' पीडीओ समर्थन की आवश्यकता है.<br>'.$MULTILANG_ReinicieWeb;
	$MULTILANG_ErrDriverPDO=$MULTILANG_PHPSinSoporte.' for PDO. '.$MULTILANG_ReinicieWeb;
	$MULTILANG_ObjetoNoExiste='इस अनुरोध के साथ जुड़े वस्तु मौजूद नहीं है.';
	$MULTILANG_ErrorDatos='इनपुट डेटा में समस्या';
	$MULTILANG_ErrorTitAuth='<blink>पहुंच अस्वीकृत!</blink>';
	$MULTILANG_ErrorDesAuth='<div align=left>प्रणाली का उपयोग करने के लिए आपूर्ति की क्रेडेंशियल्स स्वीकार नहीं किया गया। कुछ आम कारण होते हैं:<br><li>उपयोगकर्ता नाम या पासवर्ड ग़लत है. <br> <li> सुरक्षा कोड गलत दर्ज. <br> <li> अपना लॉगिन अक्षम लोगों के लिए है. <br> <li> खाता गलत पासवर्ड के साथ कई प्रयासों के द्वारा उपयोग बंद कर दिया.</div>';
	$MULTILANG_ErrorSoloAdmin='केवल व्यवस्थापक उपयोगकर्ता डिबग मोड के साथ लेन-देन के विवरण पर दिया देख सकते हैं';
	$MULTILANG_ErrGoogleAPIMod='OAuth2 गूगल के लिए डिफ़ॉल्ट प्रमाणन पद्धति के रूप में विन्यस्त किया गया था.<br>Anyway the Practicos module for google-api is not installed yet.<br>Please download the google-api module from Practicos website and reload again.';
	$MULTILANG_ErrFuncion='<br>PHP समारोह नहीं मौजूद है या अपने सर्वर में अक्षम है करता है: ';
	$MULTILANG_ErrDirectiva='पर्यावरण वर अपने PHP या वेब सर्वर विन्यास पर सक्रिय किया जाना चाहिए';
	$MULTILANG_UsuariosChat='वे व्यवस्था करने के लिए फिर से प्रवेश जब इस पल में ऑफ़लाइन हैं कि उपयोगकर्ता सभी संदेशों को देखेंगे।';
    $MULTILANG_AdminArchivos='फ़ाइल प्रबंधक';
    $MULTILANG_ErrorConnLDAP='एक त्रुटि LDAP सर्वर कनेक्शन के दौरान हुई। कृपया अपनी सेटिंग देखें और पुनः प्रयास करें। विवरण:<br>';
    $MULTILANG_ErrorRW='फ़ाइल लिखने के लिए अधिकार नहीं है! इसकी सामग्री में कोई परिवर्तन खो दिया जा सकता है';
    $MULTILANG_ErrorExistencia='आप संस्करण के लिए कहा फ़ाइल नाम नहीं मौजूद करता है!';
    $MULTILANG_ErrorNoACE='ऐस मॉड्यूल फ़ाइल संपादित करने की कोशिश नहीं मिला था';
    $MULTILANG_AyudaExplorador='महत्वपूर्ण: यह केवल मौजूद है के बारे में कुछ फ़ोल्डरों जानकारी के रूप में दिखाया जाता है। वे संपादन योग्य फ़ाइलों ही किया है, शायद, फ़ोल्डरों का विस्तार.';
    $MULTILANG_EnlacePcoder='{PCoder}: कोड संपादक';
    $MULTILANG_AtajosTitPcoder='कुंजीपटल संक्षिप्त रीति';
    $MULTILANG_AvisoSistema='सिस्टम संदेश';
    $MULTILANG_PcoderAjuste='विंडो समायोजन';
    $MULTILANG_PcoderAjusteConfirma='आप अपनी अधिकतम संकल्प के रूप में खिड़की के आकार करने के लिए इस विंडो को फिर से लोड करने के लिए जा रहे हैं। आप इस विंडो को फिर से लोड जब आप पहले से ही बचाया न कि किसी भी परिवर्तन खो सकते हैं। क्या आप जारी रखना चाहते हैं?';
    $MULTILANG_BuscaCriterios='आप खोज करने के लिए एक महत्वपूर्ण शब्द दर्ज करना चाहिए';
    $MULTILANG_EstadoPHP='PHP जानकारी';

	//Asistente disenador aplicaciones
	$MULTILANG_DesAppBoton='आवेदन डिजाइन';
	$MULTILANG_TitDisenador='आवेदन डिजाइन <b>सरल और तेज है:</b>';
	$MULTILANG_DefTablas='तालिका परिभाषा';
	$MULTILANG_DesTablas='टेबल्स जानकारी उनके साथ जुड़े रूपों का उपयोग कर संग्रहीत किया जाता है, जिसमें उन संरचनाओं हैं.';
	$MULTILANG_DefForms='डेटा प्रविष्टि और क्वैरी जानकारी के लिए';
	$MULTILANG_DesForms='वे उपयोगकर्ता, कुछ सत्यापन या प्रारूपों के अनुसार जानकारी दर्ज परामर्श करें या यहाँ तक के रिकॉर्ड को नष्ट करने की अनुमति देते हैं। प्रदर्शन भी ऐसे पन्नों या पहले से डिज़ाइन रिपोर्ट के रूप में अन्य तत्वों की अनुमति देते हैं.';
	$MULTILANG_DefInformes='(ग्राफिक्स या टेबल)';
	$MULTILANG_DesInformes='वे परिभाषित विभिन्न स्वरूपों और फिल्टर में उपयोगकर्ताओं के लिए टेबल के भीतर सूचना मौजूदा प्रस्तुत करते हैं। आप सारणीबद्ध या चार्ट प्रकार बना सकते हैं और बाद में भी अन्य स्थानों में एम्बेडेड हो.';
	$MULTILANG_DefMenus='उपयोगकर्ताओं के लिए';
	$MULTILANG_DesMenus='कि अनुमति के साथ एक उपयोगकर्ता द्वारा चयनित किया जा सकता है कि चित्रमय प्रतीक और पाठ विवरण के साथ रूपों या रिपोर्टों के रूप में तैयार लिंक वस्तुओं। यह भी आप बाहरी कार्यों या कस्टम आदेश निष्पादन लिंक करने के लिए अनुमति देता है.';
	$MULTILANG_UsuariosPermisos='उपयोगकर्ता और अनुमतियाँ';
	$MULTILANG_DefUsuarios='अपने आवेदन का उपयोग करने के लिए';
	$MULTILANG_DesUsuarios='पहुँच प्रपत्र, रिपोर्ट या किसी भी पहले से परिभाषित मेनू विकल्पों के लिए प्रत्येक के लिए उपलब्ध प्रत्येक उपयोगकर्ता के लिए पहुँच साख, और अनुमतियाँ सेट करता है.';
	$MULTILANG_DefAvanzadas='अग्रिम औज़ार';
	$MULTILANG_DefMantenimientos='रखरखाव';
	$MULTILANG_DefPcoder='ऑनलाइन कोड संपादक';
	$MULTILANG_DefLimpiarTemp='स्वच्छ अस्थायी फ़ोल्डर /tmp';

	//Cierre de sesion
	$MULTILANG_SesionCerrada='आपका सत्र बंद कर दिया गया है';
	$MULTILANG_TituloCierre='इस तरह उपयोगकर्ता द्वारा की गई कार्रवाई से परिणाम कर सकते हैं';
	$MULTILANG_ExplicacionCierre='<li>स्वेच्छा से अपने सत्र बंद</li>
			<li>एक लंबे समय के लिए इस प्रणाली का उपयोग कर बंद करो</li>
			<li>व्यवस्थापक द्वारा प्रतिबंधित वर्गों में एक ही समय प्रणाली पर खुले कई खिड़कियों के बाद</li>
			<li>आपका उपयोगकर्ता नाम या पासवर्ड आगे ऑपरेशन के लिए अमान्य है</li>
			<li>अनुमति दी उन लोगों से लिंक या अन्य बटन का उपयोग नेविगेट</li>
			<br><strong>यह भी पसंद कर अपने कंप्यूटर पर विन्यास या कार्रवाई के लिए:</strong><br>
			<li>आपका ब्राउज़र कुकीज़ का समर्थन नहीं है</li>
			<li>ब्राउज़र कुकीज़ या सत्र की साफ कैश प्रणाली का उपयोग करते हुए</li>
			<br><strong>सिस्टम विन्यास भी पसंद:</strong><br>
			<li>आप मंच की स्थापना की प्रक्रिया के सत्र की एक पुनः आरंभ करने की आवश्यकता पूरी कर ली है</li>
			<li>उपयोगकर्ता के साइन कुंजी इस प्रणाली के लिए आवश्यक कुंजी से मेल खाती नहीं करता</li>
			<li>एक ऑपरेशन पर हस्ताक्षर करने के लिए क्रेडेंशियल्स मान्य नहीं हैं</li>';

	//Actualizacion de plataforma
	$MULTILANG_ActMsj1='ATTENTION: Please read this information before continuing';
	$MULTILANG_ActMsj2='Pr&aacute;ctico provides this mechanism to implement automatic updates to your system with incremental patches downloaded from the official website or by project wizard for updates, however, before applying any patch is essential that:<br><br>
			<li>Make a backup of your databases. Some updates may require modification of structures on the basis of data information that may affect.
			<li>Back up your files or Practico folder.
			<li>CLEAN the Practico working folder (path tmp /) it will be used by the wizard to decompress and scan files.';
	$MULTILANG_ActUsando='Currently you are using version';
	$MULTILANG_ActPaquete='Package / Manual update Patch';
	$MULTILANG_ActSobreescritos='Previous files will be overwritten';
	$MULTILANG_CargarArchivo='Upload file';
	$MULTILANG_Adjuntando='Attaching a new file to the system';
	$MULTILANG_ErrorTamano='<b> WARNING: </b> interrupted process. The file exceeds the size limit';
	$MULTILANG_ErrorFormato='<b> WARNING: </b> interrupted process. The format of the uploaded file is not valid';
	$MULTILANG_CargaCorrecta='The file has been uploaded correctly';
	$MULTILANG_ErrorDesconocido='<b> WARNING: </b> An unknown error occurred while uploading the file';
	$MULTILANG_ErrorDescomprimiendo='Unpacking file';
	$MULTILANG_ContenidoParche='File contents';
	$MULTILANG_ErrorVerAct='Error loading the current version of Practico. File not found';
	$MULTILANG_ErrorActualiza='The uploaded file does not appears to be a valid upgrade package. File not found';
	$MULTILANG_ErrorAntigua='The uploaded patch file references a oldest update that your current version';
	$MULTILANG_ErrorVersion='The uploaded patch file requires the following version';
	$MULTILANG_AvisoIncremental='You must first apply incremental patches required to raise their minimum system version that requires patch.';
	$MULTILANG_Integridad='Integrity';
	$MULTILANG_ResumenParche='Summary of changes and functionalities provided by the patch';
	$MULTILANG_ResumenInstrucciones='Instructions to be executed on system tables';
	$MULTILANG_FinRevision='REVIEW PROCESS FINISHED';
	$MULTILANG_ActMsj3='In applying the above listed files will upgrade your system to the next version';
	$MULTILANG_ActErrGral='File structure, type or version unsupported';
	$MULTILANG_ActDesde='Updating from version';
	$MULTILANG_ErrLista='Error loading list of files to backup';
	$MULTILANG_HaciendoBkp='Making backup';
	$MULTILANG_ErrBkpBD='An error occurred during the database backup';
	$MULTILANG_ActMsj4='If any of the files could not be written by this wizard by permissions issues, the patch can also be applied manually by the administrator or by copying only files missing';
	$MULTILANG_ActMsj5='File structure or type unsupported';
	$MULTILANG_ActAlertaVersion='There is a new version of Practico available to download.<br>We recomend you to download the new version or upgrade package from the oficial website and upgrade your system to have the new features.';
	$MULTILANG_ActBuscarVersion='Look for new versions automatically';
    $MULTILANG_ActErrEscritura='Write error';
    $MULTILANG_ActDesEscritura='WARNING: There are write errors in the files that are going to be upgraded.
        <br><br>To keep the integrity in the software you cant upgrade until you fix the file permissions to be writeable by Practico.  Files are marked in the list in red color and the text "'.$MULTILANG_ActErrEscritura.'".  
        <br><br>Fix the problem and try again.';
    $MULTILANG_ActBackupTipo='Backup mode';
    $MULTILANG_ActBackup1='Scripts replaced during this process only';
    $MULTILANG_ActBackup3='Scripts replaced and all my database';
    $MULTILANG_ActBackupDes='Doing a full backup could be a heavy task for the system.  In systems widely used a full backup process should be done by another tool that allow you to have consistent files even with users working on the fly.';

	//Formularios
	$MULTILANG_ErrFrmDuplicado='Failed duplicated value in the field. The value you entered already exists in the database. Field: ';
	$MULTILANG_ErrFrmObligatorio='You forgot to enter mandatory field: ';
	$MULTILANG_ErrFrmDatos='There is a problem in the input data';
	$MULTILANG_ErrFrmCampo1='You must enter a valid title or label for the field.';
	$MULTILANG_ErrFrmCampo2='You must enter a valid field to link to the data table associated with the form.';
	$MULTILANG_ErrFrmCampo3='You must enter a valid title or label for the button.';
	$MULTILANG_ErrFrmCampo4='You must enter a valid action to be executed when control is activated.';
	$MULTILANG_FrmMsj1='Add an item to the form';
	$MULTILANG_FrmTipoObjeto='Type of object to add';
	$MULTILANG_FrmTipoTit1='Data Controls';
	$MULTILANG_FrmTipo1='Short text field';
	$MULTILANG_FrmTipo2='Free/Unlimited text field';
	$MULTILANG_FrmTipo3='Richly formatted text field (CKEditor)';
	$MULTILANG_FrmTipo4='Selection field (ComboBox dropdown list)';
	$MULTILANG_FrmTipo5='Selection field (RadioButton)';
	$MULTILANG_FrmTipoTit2='Presentation and other content';
	$MULTILANG_FrmTipo6='Rich Text (as a label)';
	$MULTILANG_FrmTipo7='Wrapper (iFrame)';
	$MULTILANG_FrmTipoTit3='Internal objects';
	$MULTILANG_FrmTipo8='Report predesigned (Data Table or Graph)';
	$MULTILANG_FrmTipo9='Slider (numeric range selector - HTML5)';
	$MULTILANG_FrmTipo10='Password field';
	$MULTILANG_FrmTipo11='Field value as label';
	$MULTILANG_FrmTipoTit4='Special Data Controls';
	$MULTILANG_FrmTipo12='Archivo adjunto';
	$MULTILANG_FrmTipo13='Canvas (Drawing area - HTML5)';
	$MULTILANG_FrmTipo14='Canvas (Webcam capture - HTML5)';
	$MULTILANG_FrmTipo15='SubForm (To query and ReadOnly)';
    $MULTILANG_FrmTipo16='Command button';
    $MULTILANG_FrmTipo17='Richly formatted text field (Responsive)';
	$MULTILANG_FrmTipo18='Verify field (CheckBox)';
	$MULTILANG_FrmTipoPincel='Brush size';
	$MULTILANG_FrmTipoColor='Line color';
	$MULTILANG_FrmTipoAdvertencia='This kind of data controls should be stored in your table into a long text or unlimited field';
	$MULTILANG_FrmValorMinimo='Minimum value';
	$MULTILANG_FrmValorMaximo='Maximum value';
	$MULTILANG_FrmValorSalto='Step value';
	$MULTILANG_FrmTitValorSalto='How many units jump the slider on each movement?';
	$MULTILANG_FrmTitulo='Title or Tag';
	$MULTILANG_FrmDesTitulo='Text that will appear next to the field telling the user the information that must be entered. You can use basic HTML to additional format.';
	$MULTILANG_FrmCampo='Linked field';
	$MULTILANG_FrmFiltroLista='List filter condition';
	$MULTILANG_FrmDesFiltroLista='Special condition that records must have to be displayed.  This condition could use any field in your source table that are not selected as values too.  Fixed values should be enclosed in double cuotes and you can use another expresions like ORDER BY, GROUP BY, LIMIT, Etc. This field will be added after a WHERE clausule in the query.  REMEMBER: If you dont have a Condition but you want a ORDER BY OR GROUP BY then add at least an 1=1 before to apply to the condittion. You could use {$Variable} to refer a PHP Variable too';
	$MULTILANG_FrmCampoOb1='Mandatory field for data binding controls';
	$MULTILANG_FrmDesCampo='Field data table which will link information.  In file fields this could contain the relative path to the file uploaded in the server.  Every file should have at least one field to store its path';
	$MULTILANG_FrmValUnico='Single value field';
	$MULTILANG_FrmTitUnico='Uniqueness for input values';
	$MULTILANG_FrmDesUnico='Indicates whether the field can store or repeated values ​​in the database. Should be enabled for fields representing primary keys in their Design and disabled for the rest.  You should take care in that forms that you need this field to do upgrades and its duplicated error message.';
	$MULTILANG_FrmPredeterminado='Default value';
	$MULTILANG_FrmDesPredeterminado='Sets the value that appears automatically filled in the field to open the form view. This value can be out of data validation.  If a PHP session variable is entered then Practico will take its value.';
	$MULTILANG_FrmValida='Data validation';
	$MULTILANG_FrmValida1='Numbers only 0-9';
	$MULTILANG_FrmValida2='Only letters A-Z';
	$MULTILANG_FrmValida3='Letters and numbers';
	$MULTILANG_FrmValida4='Date field using unified calendar';
	$MULTILANG_FrmValida7='Date field using separated pickers (year, month and day)';
	$MULTILANG_FrmValida5='Time field';
	$MULTILANG_FrmValida6='Date and Time field';
	$MULTILANG_FrmValida8='Date and Time field using unified selector';
	$MULTILANG_FrmValidaDes='Filter type to be applied when the user enters information by keyboard';
	$MULTILANG_FrmLectura='Read only field';
	$MULTILANG_FrmTitLectura='Defines whether you can change its value or not';
	$MULTILANG_FrmDesLectura='Property useful for fields or forms from the user query which is required to display the value but not allow modification';
	$MULTILANG_FrmAyuda='Help title';
	$MULTILANG_FrmDesAyuda='Text that will appear as a header for the field help text explaining to the user what to enter';
	$MULTILANG_FrmTxtAyuda='Help text';
	$MULTILANG_FrmDesTxtAyuda='Full Text with summary function description for the field. You can include formatting instructions, warnings or any other message to the user';
	$MULTILANG_FrmDesPeso='Position in which the field appears on the form when it is displayed on screen. Order.';
	$MULTILANG_FrmDesColumna='Column to locate the field when the form view has multiple columns. Those fields larger than the defined columns in the form will not be drawn';
	$MULTILANG_FrmObligatorio='Mandatory';
	$MULTILANG_FrmVisible='Visible';
	$MULTILANG_FrmDesVisible='Determines whether the control is visible or not to the user. If left control is not used but as a hidden';
	$MULTILANG_FrmLblBusqueda='Use for record search? Label';
	$MULTILANG_FrmTitBusqueda='Indicates whether the field is used to search for records';
	$MULTILANG_FrmDesBusqueda='Leave blank to indicate that it is a normal field or enter the label that should go in the command button located on the right side to make the search for records';
	$MULTILANG_FrmAjax='Use AJAX to search';
	$MULTILANG_FrmTitAjax='Record Recovery Mode';
	$MULTILANG_FrmDesAjax='When the box is turned on, Practico attempts to retrieve the log information to the form using AJAX. In a combo box that takes its values from a table you can use it to add a button to refresh its contents online.';
	$MULTILANG_FrmTeclado='Add virtual keyboard';
	$MULTILANG_FrmTitTeclado='Allow data entry by on-screen keyboard';
	$MULTILANG_FrmDesTeclado='When enabled on the form displays a virtual keyboard for entering information,. For now the keyboard use may violate validations';
	$MULTILANG_FrmAncho='Width';
	$MULTILANG_FrmTitAncho='How wide should occupy space control';
	$MULTILANG_FrmDesAncho='IMPORTANT: in characters number for simple text fields and pixels rich-text fields. Enter a number of columns, however, note that the width in pixels will vary according to the type of font used by the current theme.  For image or bar code fields this value is for the size of the picture.';
	$MULTILANG_FrmDesAncho2='Minimum recommended for rich-text format fields: 350';
	$MULTILANG_FrmAlto='Height (lines)';
	$MULTILANG_FrmTitAlto='How many rows should be visible in the control?';
	$MULTILANG_FrmDesAlto='IMPORTANT: the number of rows for simple text or in pixels for rich-text formatting. If the text exceeds the number of rows are automatically added scrollbars.  For image or bar code fields this value is for the size of the picture.';
	$MULTILANG_FrmDesAlto2='Minimum recommended format fields: 100';
	$MULTILANG_FrmBarra='Formatting bar';
	$MULTILANG_FrmBarraCKEditor='Disponibles para CKEditor';
	$MULTILANG_FrmBarraSummer='Disponibles para SummerNote (Responsive)';
	$MULTILANG_FrmBarraTipo1='Basic: Document, character and paragraph formatting';
	$MULTILANG_FrmBarraTipo2='Standard: Basic + links and font styles';
	$MULTILANG_FrmBarraTipo3='Extended: Standard + clipboard, search-replace and spelling';
	$MULTILANG_FrmBarraTipo4='Advanced: Extended + Insert objects and colors';
	$MULTILANG_FrmBarraTipo5='Full: Advanced + Forms and full screen';
	$MULTILANG_FrmBarraTipo1Summer='Basic: Character and paragraph formatting';
	$MULTILANG_FrmBarraTipo2Summer='Standard: Basic + font styles';
	$MULTILANG_FrmBarraTipo3Summer='Extended: Standard + Tables, links and lines';
	$MULTILANG_FrmBarraTipo4Summer='Advanced: Extended + FullScreen and HTML Source';
	$MULTILANG_FrmBarraTipo5Summer='Full: Advanced + Insert images and videos';
	$MULTILANG_FrmTitBarra='Editor type used';
	$MULTILANG_FrmDesBarra='Indicates the type of toolbar that appears at the top of the control and the user to perform different tasks of editing. IMPORTANT: Each type of editor requires a different space on the form as it should deploy a number of icons and different options';
	$MULTILANG_FrmFila='Single row for this object?';
	$MULTILANG_FrmTitFila='Must Practico use a full row for the object?';
	$MULTILANG_FrmDesFila='Allows to display the object in a unique row of the table used in the form';
	$MULTILANG_FrmLista='Options list';
	$MULTILANG_FrmTitLista='What options are to be chosen.  Enter a comma character only to say Practico that put an empty value at the beginning.  Leave in blank to use as default the first record founded.';
	$MULTILANG_FrmDesLista='Enter a list of options separated by commas. If you need to take the options table dynamically from another application to use the Data Source fields for options. Should fill both options (fixed list and data source) the result will be the combination';
	$MULTILANG_FrmDesLista2='Commas separated';
	$MULTILANG_FrmOrigen='Options list source';
	$MULTILANG_FrmTitOrigen='You must specify the same source (table) from the list of values';
	$MULTILANG_FrmDesOrigen='From which Field are made the choices that displays the list';
	$MULTILANG_FrmTitOrigen2='What is this?';
	$MULTILANG_FrmOrigenVal='List of values source';
	$MULTILANG_FrmTitOrigenVal='You must specify the same source (table) from the list of options';
	$MULTILANG_FrmDesOrigenVal='Field from which values ​​are taken internally (to be processed) for each option in the list';
	$MULTILANG_FrmEtiqueta='Value of the label (it will be printed on the form in HTML format)';
	$MULTILANG_FrmURL='IFrame URL';
	$MULTILANG_FrmDesURL='Enter the address of the page that will be embedded in the IFrame';
	$MULTILANG_FrmInforme='Linked report';
	$MULTILANG_FrmFormulario='Linked Subform';
	$MULTILANG_FrmDesCampoVinculo='Put here the local fields name (parent form field) to be used for search data in the sub-form';
	$MULTILANG_FrmDesCampoForaneo='Put here the Foraign filed from the subform to be used to compare or search data in the local field to show data.';
	$MULTILANG_FrmVentana='Create a window for the object?';
	$MULTILANG_FrmDesVentana='It is NOT recommended to activate this field when you want to embed GRAPHIC type reports';
	$MULTILANG_FrmLongMaxima='Maximum length';
	$MULTILANG_FrmTit1LongMaxima='How many characters can the field store?';
	$MULTILANG_FrmTit2LongMaxima='Value between 1 and N, 0 to disable limits';
	$MULTILANG_FrmBtnGuardar='Add or update the object / field';
	$MULTILANG_FrmAgregaBot='Add buttons and actions to form';
	$MULTILANG_FrmTituloBot='Title or Tag';
	$MULTILANG_FrmDesBot='Text to appear on the button';
	$MULTILANG_FrmEstilo='Style';
	$MULTILANG_FrmDesEstilo='Graphical appearance for the control';
	$MULTILANG_FrmTipoAccion='Action type';
	$MULTILANG_FrmAccionT1='Internal actions';
	$MULTILANG_FrmAccionGuardar='Save data';
	$MULTILANG_FrmAccionLimpiar='Clean data';
	$MULTILANG_FrmAccionEliminar='Delete data (requires a unique value field ,even hidden)';
	$MULTILANG_FrmAccionActualizar='Update data';
	$MULTILANG_FrmAccionRegresar='Go back to desktop';
	$MULTILANG_FrmAccionCargar='Object load';
	$MULTILANG_FrmAccionT2='User defined';
	$MULTILANG_FrmAccionExterna='In personalizadas.php or any other module installed';
	$MULTILANG_FrmAccionJS='JavaScript command';
	$MULTILANG_FrmDesAccion='Command to be run when clicked control. For actions defined is personalizadas.php form data will be sent to that routine for processing';
	$MULTILANG_FrmAccionCMD='User command';
	$MULTILANG_FrmAccionDesCMD='Action name that should exists in personalizadas.php or any other module that will process the information or a JavaScript command to be executed inmediately for the App (if you need to send some parameter you could use sigle quotes to enclose them). If you need to load Practicos Objects like a forms or report you could use the same sintax used for menues items: frm:XX:Par1:Par2:ParN o inf:XX...  There is a javascript command available called ImprimirMarco(\'MARCO_IMPRESION\') that let you print the active form content.  You can use commands like PCO_VentanaPopup(\'http://www.google.com\',\'YourTitle\',\'toolbar=no, location=no, directories=no, status=no, menubar=no ,scrollbars=no, resizable=yes, fullscreen=no, width=640, height=480\'); .Check docs for a complete guide.';
	$MULTILANG_FrmDesPeso='Position in which the field appears in the status bar of the form when it is displayed on screen. Order from left to right';
	$MULTILANG_FrmBotDesVisible='Determines whether the control is visible or not to the user';
	$MULTILANG_FrmRetorno='Return title';
	$MULTILANG_FrmDesRetorno='Text that will appear as a header on the desktop after performing the action indicated by the user';
	$MULTILANG_FrmTxtRetorno='Return text';
	$MULTILANG_FrmTxtDesRetorno='Full Text with description of action taken or delivered to the user message after running control';
	$MULTILANG_FrmTxtRetornoIcono='Iconf for return';
	$MULTILANG_FrmTxtDesRetornoIcono='Set an icon to put in the message.  Use AwesomeFonts notation.  I.E.:  fa-info-circle  to show an information icon.';
	$MULTILANG_FrmTxtRetornoEstilo='CSS style for the return message (if applies)';
	$MULTILANG_FrmConfirma='Confirmation Text';
	$MULTILANG_FrmDesConfirma='If its filled, Text that will appear as a popup warning control execution and waiting for user confirmation to proceed';
	$MULTILANG_FrmBtnGuardarBut='Add Action / Button';
	$MULTILANG_FrmDisCampos='General fields design';
	$MULTILANG_FrmDesObliga='Note that the required fields should be visible';
	$MULTILANG_FrmGuardaCol='Save column';
	$MULTILANG_FrmAumentaPeso='Increase weight (down)';
	$MULTILANG_FrmDisminuyePeso='Decrease Weight (up)';
	$MULTILANG_FrmHlpCambiaEstado='Change status';
	$MULTILANG_FrmAdvDelCampo='IMPORTANT: Deleting this field users can not see it and you can not undo this operation.\n'.$MULTILANG_Confirma;
	$MULTILANG_FrmTitComandos='General definition of actions and commands';
	$MULTILANG_FrmTipoAcc='Action type';
	$MULTILANG_FrmAccUsuario='User action';
	$MULTILANG_FrmOrden='Command';
	$MULTILANG_FrmAdvDelBoton='IMPORTANT: When removing the button / action users can not view or run the command associated with this and you can not undo this operation later.\n'.$MULTILANG_Confirma;
	$MULTILANG_FrmObjetos='Objects and Data Fields';
	$MULTILANG_FrmDesObjetos='Add an object or data field';
	$MULTILANG_FrmDesCampos='Fields general design';
	$MULTILANG_FrmAcciones='Actions, buttons and commands';
	$MULTILANG_FrmDesBoton='Add button or action';
	$MULTILANG_FrmDesAcciones='General definition of actions';
	$MULTILANG_FrmVolverLista='Back to list of forms';
	$MULTILANG_FrmErr1='You must enter a valid title for the form.';
	$MULTILANG_FrmErr2='Please specify a valid name for the data table associated with the form.';
	$MULTILANG_FrmAgregar='Add New Form';
	$MULTILANG_FrmActualizar='Update initial configurations';
	$MULTILANG_FrmDetalles='Define the form details';
	$MULTILANG_FrmTitVen='Window title';
	$MULTILANG_FrmDesTit='Text that appears at the top of the window';
	$MULTILANG_FrmHlp='Help Title';
	$MULTILANG_FrmDesHlp='Text that will appear as a caption for the support of the form';
	$MULTILANG_FrmTxt='Help Text';
	$MULTILANG_FrmDesTxt='Full Text with summary function description for the form. Introductory text for any user';
	$MULTILANG_FrmImagen='Background color';
	$MULTILANG_FrmImagenDes='If your web browser has HTML5 support you could choose the background color.  If not you can type an hexadecimal color code i.e. #F2F2F2 or its name as HTML notation i.e. LightGray';
	$MULTILANG_FrmNumeroCols='Number of columns';
	$MULTILANG_FrmDesNumeroCols='Indicates how many columns to be deployed in fields when the form is loaded';
	$MULTILANG_FrmCreaDisena='Create and design';
	$MULTILANG_FrmTitForms='Forms defined in the system';
	$MULTILANG_FrmCamposAcciones='Fields and actions';
	$MULTILANG_FrmAdvDelForm='IMPORTANT: Deleting the form users can not access it again to query operations or data entry defined. You can not undo this operation. This also eliminates any internal design of the form.\n'.$MULTILANG_Confirma;
	$MULTILANG_FrmAdvScriptForm='Scripts edit (Advanced)';
	$MULTILANG_FrmHlpFunciones='All JavaScript functions defined here will be included in the form.<br>If you need some additional events linked by buttons or any object in the form<br> this field let you define them.<br><b>When you need to use parameters or any quote use always double quotes!</b>.<br>The FrmAutoRun function must be exist (even empty) cause it will be executed automatically on every form load.';
    $MULTILANG_FrmHlpFinalFunciones='This code is a part of your form.  Close and clic Save/Update form to apply changes.';
	$MULTILANG_FrmCopiar='Make a copy';
	$MULTILANG_FrmAdvCopiar='A new copy of this object will be created.  Are you sure?';
	$MULTILANG_FrmMsjCopia='Now you can go to edit your new object.  A copy was maded as: ';
	$MULTILANG_FrmBordesVisibles='Are table borders visible?';
	$MULTILANG_FrmFormatoSalida='Output format';
	$MULTILANG_FrmPlantillaArchivo='Name template for the file';
	$MULTILANG_FrmDesPlantillaArchivo='The template is the form or pattern that will be renamed the file after the user uploaded to the server. This may include different variables to alter the name and extension thereof as examples. You can also leave it blank so that the files are loaded with the original name of the folder system loads (not recommended for security).';
	$MULTILANG_FrmErrorCargaGeneral='There was an error during the upload';
	$MULTILANG_FrmErrorCargaTamano='The file size is greater than the allowed size';
	$MULTILANG_FrmPlantillaEjemplos='<i>Some format modifiers:<li>_ORIGINAL_ : Original file name</li><li>_CAMPOTABLA_ : Linked field name over the table</li><li>_FECHA_ : Actual date in AAAAMMDD format</li><li>_HORA_ : Actual server time in  HHMMSS format</li><li>_MICRO_ : Time microseconds</li><li>_HORAINTERNET_ : Internet time between 000 and 999</li><li>_USUARIO_ : User login name</li></i><b>Examples:</b><li>_USUARIO__ORIGINAL_: Renames the original file with the user name login</li><li>formatos/_ORIGINAL_: Will upload the file into a formatos/ folder using the original name.  This folder have to be created by admin user before using the file manager in the cargas folder.</li><li>_FECHA__HORA__USUARIO_.pdf: Renames all the original file for something like 20140502_135400_admin.pdf</li><li>reportes/_FECHA_.xls: Will upload the file into reportes folder and will force the final extension to .xls too.</li><li>foto__USUARIO_.jpg: This file will have two fixed strings (foto_ at beginning and .jpg at the end) but inside them Practico will append the username.  Pay attention to the double underline character, one of them will separate the name and the other is for the format modifier.  You will obtain somthing like foto_avelez.jpg</li>A general rule: any string inside the pattern that dont match any format modifier will be a fixed string in the file name.';
	$MULTILANG_FrmArchivoLink='[Open already uploaded file]';
	$MULTILANG_FrmCanvasLink='[Open drawing already added]';
	$MULTILANG_FrmErrorCam='There is an error with the video device.  Please cheack that you have a video device or webcam installed and the you answer Afirmative or Accept in your browser to allow Practico to use the device.';
    $MULTILANG_FrmPestana='Forms tab title in which the control will be published';
    $MULTILANG_FrmDesPestana='Assign the tab for this object in the form.  Practico automatically creates tabs according to the values entered in each object.';
    $MULTILANG_FrmTagPersonalizado='HTML Custom Tag';
    $MULTILANG_FrmDesTagPersonalizado='Allow to add parameters to the HTML Tag created over the form by Practico. 
            <hr>Some examples according to the data control type:
            <br><b>Select lists (combo-box):</b>
                <li><u>data-live-search=true</u> Enable search field in a list.</li>
                <li><u>multiple</u> Enable multiple select.</li>
                <li><u>data-selected-text-format=count</u> Count selected items instead values.</li>
                <li><u>data-max-options=#</u> Maximum of elements selected.
                <li><u>data-size=auto|#</u> How many rows are showed in the item list.</li>
                <li><u>data-style=btn-primary|btn-info|btn-success|btn-warning|btn-danger|btn-inverse</u> Graphic style
                <li><u>disabled</u> Disables the control</li>
            <br><b>Botones de comando (command buttons):</b>
                <li><u>btn btn-xs btn-primary|btn-info|btn-success|btn-warning|btn-danger|btn-inverse</u></li>';
    $MULTILANG_FrmBtnFull='Load in FullScreen';
    $MULTILANG_FrmBtnObjetivo='HTML Target';
    $MULTILANG_FrmActualizaAjax='Dynamic reload';
    $MULTILANG_FrmActivarInline='<i>Inline</i> view: Work in onjunction with next and previous elements';
    $MULTILANG_FrmActivarInlineDes='Allow to put the control using an inline style to keep a new line before publish the control over the form. Acording the effect you want, previous or next element should activate this properti too';
    $MULTILANG_FrmTipoCopia='Select what kind of copy do you want';
    $MULTILANG_FrmTipoCopia1='Online';
    $MULTILANG_FrmTipoCopia2='XML with current ID';
    $MULTILANG_FrmTipoCopia3='XML with dynamic ID';
    $MULTILANG_FrmTipoCopiaDes1='Online: Creates a new object with a new ID.  That includes all the components linked to allow you create new forms or reports from an existing object. This works inmediately over the running system, cloning the selected object.';
    $MULTILANG_FrmTipoCopiaDes2='XML with current ID: Exports/Imports the object using XML sintax to allow you import it over other system using the current ID.  Usefull if you want to overwrite forms or reports with enhacements from other systems.';
    $MULTILANG_FrmTipoCopiaDes3='XML with dynamic ID: Exports/Imports the object using XML sintax but the new ID for the object is generated dinamically each time you import the file, with a different ID.  Usefull to replicate the functionallity of "Online" option but over differents systems.';
	$MULTILANG_FrmTipoCopiaExporta='Copying / Exporting';
	$MULTILANG_FrmCopiaFinalizada='The copy process already finished.  You could click on donwload button to get the XML file.';
	$MULTILANG_FrmImportar='Import a design from a file';
	$MULTILANG_FrmImportarConflicto='There are conflicts that you need to solve before continue with the importing process';
	$MULTILANG_FrmImportarGenerado='New object has been created';
	$MULTILANG_FrmImportarAlerta='An element with the same internal ID and type that you want to import was founded in the system.  The file that you want to import will delete  the actual object and will fill it with the elements in the file.  We recommend you to check previously if you really want to overwrite the element before continue.';
	$MULTILANG_FrmValOnCheck= 'Value when is activated';
	$MULTILANG_FrmValOffCheck='Value when is not activated';
	$MULTILANG_FrmValCheckDes='Define the value to be assigned to the field that will be stored in the database according to the control status';
	
	//Informes
	$MULTILANG_InfErr1='You must specify values ​​for the fields corresponding to at least one data series. <br> If you dont want to generate a graph then you must change the report type to data table';
	$MULTILANG_InfErr2='You must enter a valid title for the report.';
	$MULTILANG_InfErr3='Please specify a valid name for the category associated to the report.';
	$MULTILANG_InfErrCondicion='The specified condition is invalid or lacks at least one side for comparison.';
	$MULTILANG_InfErrCampo='You must enter a valid field name for the data source of the report.';
	$MULTILANG_InfErrTabla='You must enter a valid table name for the data source of the report.';
	$MULTILANG_InfErr4='You must enter a valid title or label for the button.';
	$MULTILANG_InfErr5='You must enter a valid action to be executed when control is activated.';
	$MULTILANG_InfAgregaTabla='Add a new table to the report';
	$MULTILANG_InfTablaManual='Enter a table manually';
	$MULTILANG_InfDesTablaManual='If you dont want to select a table from top list, you could type here a table name.  This option is useful when you need to access information in internal tables of Practico or tables created by other applications';
	$MULTILANG_InfAliasManual='Specify an alias manually';
	$MULTILANG_InfDesAliasManual='Useful to define the name of a table generated from a subquery or manually specified';
	$MULTILANG_InfBtnAgregaTabla='Add Table';
	$MULTILANG_InfTablasDef='Tables defined in this report';
	$MULTILANG_InfAlias='Alias';
	$MULTILANG_InfAdvBorrado='IMPORTANT: If you delete the selected object the query or report could be inconsistent.\n'.$MULTILANG_Confirma;
	$MULTILANG_InfAgregaCampo='Add a new field to the report';
	$MULTILANG_InfCampoDatos='Data Field';
	$MULTILANG_InfCampoManual='Specify a field manually';
	$MULTILANG_InfDesCampoManual='If you dont want to select a field from top list you could type here a field name.  This option is useful when you need to access information in Practico internal fields or fields created by other applications';
	$MULTILANG_InfDesAliasManual2='Useful to define the name of a field generated manually or a agrupated subquery';
	$MULTILANG_InfBtnAgregaCampo='Add Field';
	$MULTILANG_InfCamposDef='Fields defined in this report';
	$MULTILANG_InfAddCondicion='Add a new condition to the report';
	$MULTILANG_InfPrimer='First field or value';
	$MULTILANG_InfOperador='Comparison operator';
	$MULTILANG_InfSegundo='Second field or value';
	$MULTILANG_InfMayorQue='Greater than ';
	$MULTILANG_InfMenorQue='Less than';
	$MULTILANG_InfMayorIgualQue='Greater than or equal';
	$MULTILANG_InfMenorIgualQue='Less than or equal';
	$MULTILANG_InfDiferenteDe='Different';
	$MULTILANG_InfIgualA='Equal';
    $MULTILANG_InfPatron='Match pattern (Uses % as joker)';
	$MULTILANG_InfDesManual='In any manual fields you can enclose expressions or character string values ​​using double quotes.   You can compare with session vars putting the PHP variable.  i.e.: $PCOSESS_LoginUsuario, $Nombre_usuario, $Descripcion_usuario, $Nivel_usuario, $Correo_usuario, $LlaveDePasoUsuario.  If you want to use PHP variables in the middle of a string you can put it inside braces Ie: {$Variable} and they will be replaced by their global value.';
	$MULTILANG_InfOperador='Add an aggregator of expressions or a logical operator ';
	$MULTILANG_InfOpParentesisA='Parenthesis open';
	$MULTILANG_InfOpParentesisC='Parenthesis close';
	$MULTILANG_InfOpAND='AND logical';
	$MULTILANG_InfOpOR='OR logical';
	$MULTILANG_InfOpNOT='NOT';
	$MULTILANG_InfOpXOR='XOR';
	$MULTILANG_InfTitOp='When to use this option?';
	$MULTILANG_InfDesOp='If you require more than one sentence to add to its status filtering group results or require several conditions to take precedence over some operations then you can use this option. Works independently and must be added as a separate record of the consultation';
	$MULTILANG_InfReco1='Advice';
	$MULTILANG_InfReco2='Do not forget to add ANDs followed each condition linking foreign keys between different tables of the report where applicable (usually when you use more than one table).';
	$MULTILANG_InfBtnAddCondic='Add condition / operator';
	$MULTILANG_InfDefCond='Filter and conditions defined in this report';
	$MULTILANG_InfTitGrafico='Specifies types of charts to be generated by the report';
	$MULTILANG_InfSeriesGrafico1='SERIES FOR THE CHART';
	$MULTILANG_InfSeriesGrafico2='Multiple series charts must return the same number of labels';
	$MULTILANG_InfNomSerie='Series Name';
	$MULTILANG_InfCampoEtiqSerie='Label Field';
	$MULTILANG_InfCampoValor='Value field (must be numeric)';
	$MULTILANG_InfVistaGrafico1='APPEARANCE and DISTRIBUTION';
	$MULTILANG_InfVistaGrafico2='Select according to the number of desired series';
	$MULTILANG_InfTipoGrafico='Chart type';
	$MULTILANG_InfGrafico1='Horizontal Bars';
	$MULTILANG_InfGrafico2='Horizontal Bars (multiple series)';
	$MULTILANG_InfGrafico3='Line chart';
	$MULTILANG_InfGrafico4='Line chart (multiple series)';
	$MULTILANG_InfGrafico5='Vertical Bars';
	$MULTILANG_InfGrafico6='Vertical Bars (multiple series)';
	$MULTILANG_InfGrafico7='Pie chart (only one series)';
	$MULTILANG_InfActGraf='Update chart format';
	$MULTILANG_InfAgrupa='Specifies sorting criteria and grouping';
	$MULTILANG_InfReco3='Use only fields defined in your query.';
	$MULTILANG_InfCriterioAgrupa='Grouping criteria';
	$MULTILANG_InfCriterioOrdena='Ordering criteria';
	$MULTILANG_InfTitAgrupa='How the results will be grouped?';
	$MULTILANG_InfDesAgrupa='Use this option only if your report handles operations such as sum, average or count within the fields displayed. Eg SUM (field), AVG (field), COUNT (*). In that cases enter which fields (separated by comma) should group the results';
	$MULTILANG_InfTitOrdena='How the results will be sorted?';
	$MULTILANG_InfDesOrdena='To sort the results using any of the fields added. Fields must be separated by commas to sort your results, if you wish after each field can use the modifier ASC or DESC to indicate whether ascendant or descending';
	$MULTILANG_InfActCriterios='Reload sorting and grouping criteria';
	$MULTILANG_InfTitBotones='Add buttons or actions to each record';
	$MULTILANG_InfDelReg='Delete Record';
	$MULTILANG_InfCargaForm='Load a form by ID';
	$MULTILANG_InfHlpAccion='If you want to load a form use this sintax  ID:1:FieldForSearch<br>To delete the associated record type the table.field used to compare it.';
	$MULTILANG_InfVinculo='Linked field';
	$MULTILANG_InfDesVinculo='IMPORTANT: We assume the first field or column as a single and primery key value<br>
				to do removal or form opening operations.<br>
				It is recommended to use fields that has a really single value<br>
				unless you are wishing group operations.';
	$MULTILANG_InfDesPeso='Position on the button that appears within the set on the right side of each record. Order from left to right.';
	$MULTILANG_InfFiltrar='Filter results by specific conditions';
	$MULTILANG_InfCampoAgrupa='Let you grouping Sets fields for reporting operations sum, average or count and fields for the ordering of results';
	$MULTILANG_InfTablasOrigen='Source data tables';
	$MULTILANG_InfCamposOrigen='Data Fields';
	$MULTILANG_InfCondiciones='Conditions';
	$MULTILANG_InfPropGraf='Chart Properties';
	$MULTILANG_InfDesGraf='Defines the properties and appearance of the chart displayed by the report';
	$MULTILANG_InfDesAccion='Defines actions that can be performed on each record displayed by the report as Delete, Open a form, user functions, etc..';
	$MULTILANG_InfVolver='Back to list of reports';
	$MULTILANG_InfTitulo='Title of the report or chart';
	$MULTILANG_InfDesTitulo='Text that appears at the top of the generated report';
	$MULTILANG_InfDescripcion='Description';
	$MULTILANG_InfDesDescrip='Descriptive text of the report. Not in his generation but is used to guide the user in his selection';
	$MULTILANG_InfCategoria='Category';
	$MULTILANG_InfDesCateg='When the user accesses the system panel reports these are classified by categories. Enter here a category name under which you want to publish this report to the users.';
	$MULTILANG_InfNivelUsuario='User Level';
	$MULTILANG_InfTodoUsuario='All users';
	$MULTILANG_InfParam='Edit general settings of the report';
	$MULTILANG_InfTitNivel='Who can see this report?';
	$MULTILANG_InfDesNivel='Specify the user profile must be to see this report as available.';
	$MULTILANG_InfAlto='Heigth';
	$MULTILANG_InfTitAncho='Set fixed width?';
	$MULTILANG_InfDesAncho='This value also applies if you have specified a Height value. If you require the report to appear within a specified fixed width size in pixels, leave blank to be deployed data without size restrictions. In the case of chart image specifies its size.';
	$MULTILANG_InfTitAlto='Set fixed height?';
	$MULTILANG_InfDesAlto='This value also applies if you have specified a Width value. If you require the report to appear within a specified fixed width size in pixels, leave blank to be deployed data without size restrictions. In the case of chart image specifies its size.';
	$MULTILANG_InfHlpAnchoalto='Add a <b>px</b> or <b>%</b> as you need';
	$MULTILANG_InfFormato='Final format';
	$MULTILANG_InfTitFormato='How this report is displayed?';
	$MULTILANG_InfDesFormato='Indicates whether the final product will be a report of the data table or a chart.';
	$MULTILANG_InfActualizar='Refresh Report';
	$MULTILANG_InfVistaPrev='Report Preview';
	$MULTILANG_InfCargaPrev='Load preview';
	$MULTILANG_InfHlpCarga='This option will close the design mode <br> and will show you the report as it will be displayed <br> to a user of the application';
	$MULTILANG_InfErrInforme1='You must enter a valid title for the report.';
	$MULTILANG_InfErrInforme2='Please specify a valid name for the category associated with report.';
	$MULTILANG_InfTituloAgr='Add new report or chart';
	$MULTILANG_InfDetalles='Define the details of the report / chart';
	$MULTILANG_InfDefinidos='Reports / charts already defined in the system';
	$MULTILANG_InfcamTabCond='Fields, Tables and Conditions';
	$MULTILANG_InfAdvEliminar='IMPORTANT: Deleting this report users can not access it again. You can not undo this operation. This also eliminates any internal design of the report.\n'.$MULTILANG_Confirma;
	$MULTILANG_InfErrTamano='The report you are trying to generate is a graph type  report but the designer did not specify the height and width of the resulting graph.<br>Should provide an valid size of graphic to generate an image.';
	$MULTILANG_InfGeneraPDF='Allow to export this report?';
	$MULTILANG_InfGeneraPDFInfoTit='Available for tabular reports only';
	$MULTILANG_InfGeneraPDFInfoDesc='This option requires php_xml and php_zip extensions if you want to export LibreOffice, OpenOffice or Office 2007 files.  If you activate this option the report time could be more than a normal report when you have a lot of records in your results because user will launch the query to see the records on screen, and then launch the same query if he wants to export them.';
    $MULTILANG_InfVblesFiltro='Global variables required for filter';
    $MULTILANG_InfVblesDesFiltro='PHP variables (without dollar character $ and comma separated only) that should be taked from global environment to be available for filter in the condittions option while you build a query';
    $MULTILANG_InfDataTableResXPag='records per page';
    $MULTILANG_InfDataTableViendoP='Viewing page';
    $MULTILANG_InfDataTableDe='of';
    $MULTILANG_InfDataTableFiltradoDe='Filtered from';
    $MULTILANG_InfDataTableRegTotal='total records';
    $MULTILANG_InfDataTableNoDatos='No data available in table';
    $MULTILANG_InfDataTableNoRegistros='There is no records that match search criteria';
    $MULTILANG_InfDataTableNoRegistrosDisponibles='No records available';
    $MULTILANG_InfDataTableTit='DataTables support?';
    $MULTILANG_InfDataTableDes='Allow to transform the report in a DataTable to filter, search, sort and get pages of results dinamically';
    $MULTILANG_InfFormFiltrado='Form with Filter variables';
    $MULTILANG_InfFormFiltradoDes='Select a form designed to enter the filter variables for the report.  This help you to link a form that ask users for some data before to load the report.';
    $MULTILANG_InfRetornoFormFiltrado='See filtered report';
    $MULTILANG_InfAutoajusteAncho='Auto-width for generated cells';
    $MULTILANG_InfBordesCelda='Draw cell border';
    $MULTILANG_InfBordesTodos='All sides';
    $MULTILANG_InfBordesArriba='Top only';
    $MULTILANG_InfBordesAbajo='Bottomb only';
    $MULTILANG_InfBordesArrAba='Top and Bottom';
    $MULTILANG_InfBordesIzq='Left side only';
    $MULTILANG_InfBordesDer='Right side only';
    $MULTILANG_InfBordesIzqDer='Left and right sides';
	$MULTILANG_OrientacionPagina='Page layout';
	$MULTILANG_InfTamanoPapel='Paper zise';
	$MULTILANG_InfReducir='Auto-size content';
	$MULTILANG_InfTitPersonalizar='Custom presentation and layout (optional)';

	//Menus
	$MULTILANG_MnuTitEditar='Edit menu item';
	$MULTILANG_MnuSelImagen='Click on an image to select';
	$MULTILANG_MnuPropiedad='Item properties';
	$MULTILANG_MnuApariencia='APPEARANCE AND LOCATION CONFIGURATION';
	$MULTILANG_MnuTexto='Text';
	$MULTILANG_MnuPadre='Father';
	$MULTILANG_MnuSiAplica='If applies';
	$MULTILANG_MnuUbicacion='Location of this option';
	$MULTILANG_MnuArriba='TopMenu Possible?';
	$MULTILANG_MnuEscritorio='Desktop Possible?';
	$MULTILANG_MnuCentro='Middle Possible?';
    $MULTILANG_MnuIzquierda='Sidebar Possible?';
	$MULTILANG_MnuSeccion='Section';
	$MULTILANG_MnuDesArriba='You must enable this option to be displayed in the top menu-bar horizontally?';
	$MULTILANG_MnuDesEscritorio='You must enable this option to be displayed as an icon on the users desktop?';
	$MULTILANG_MnuDesCentro='You must enable this option to be deployed in the central part of the application, within windows classified / grouped by the value defined in the Section field?';
	$MULTILANG_MnuDesIzquierdo='You must enable this option to be deployed in the side bar of the application';
    $MULTILANG_MnuDesImagen='Display a list of images available on the system';
	$MULTILANG_MnuComandos='CONFIGURATION COMMANDS AND ACTIONS';
	$MULTILANG_MnuClic='Possible to click?';
	$MULTILANG_MnuURL='Static URL';
	$MULTILANG_MnuTitURL='Bring to a URL or execute a javascript?';
	$MULTILANG_MnuDesURL='Enter full URL or a command defined javascript javascript: command to be replaced within an anchor HREF generated around the object. If you need to pass string parameters to javascript commands you could use single cuotes';
	$MULTILANG_MnuTipo='Command type';
	$MULTILANG_MnuInterno='Internal';
	$MULTILANG_MnuPersonal='Personal';
	$MULTILANG_MnuObjeto='Object';
	$MULTILANG_MnuAccion='Internal action / command / object';
	$MULTILANG_MnuTitAccion='Type one of three possible values ​​as follows:';
	$MULTILANG_MnuDesAccion='1) AN OBJECT in Pr&aacute;ctico that you want to link to this menu option using this sintax frm:XXX  or  inf:XXX  where you should replace XXX with the object ID (ID form or ID for the report),  2) INTERNAL ACTION in Pr&aacute;ctico where you want to redirect the user (you can see in Practicos footer as admin), or 3) CUSTOM COMMAND: A command secuence defined by the user, this secuence should exists in personalizadas.php file or any other module installed.';
	$MULTILANG_MnuTitNivel='Who can see this option?';
	$MULTILANG_MnuDesNivel='Specify the user profile must be to see this option available.';
	$MULTILANG_MnuActualiza='Reload menu';
	$MULTILANG_MnuErr='It requires at least the text field.';
	$MULTILANG_MnuAdmin='Main menu administration';
	$MULTILANG_MnuAgregar='Add menu option';
	$MULTILANG_MnuDefinidos='Sections and menu commands defined';
	$MULTILANG_MnuNivel='Level';
	$MULTILANG_MnuComando='Command';
	$MULTILANG_MnuAdvElimina='IMPORTANT: Deleting this registry you could unlink some system options.\n'.$MULTILANG_Confirma;
	$MULTILANG_MnuHlpComandoInf='Maybe you want to add to the command this srtring <b>:htm:Informes</b>  to say Practico <br>that puts all the data in Html format and with that CSS style sheet';
	$MULTILANG_MnuHlpAwesome='You can use the same syntax used for menu icons';
    $MULTILANG_MnuTgtBlank='New window or tab';
    $MULTILANG_MnuTgtSelf='Same window or frame that it was clicked';
    $MULTILANG_MnuTgtParent='Parent frame or window';
    $MULTILANG_MnuTgtTop='Full body of the window';
    $MULTILANG_MnuTgt='Target (Only options using an URL)';
    $MULTILANG_ImagenMenu='Image: Select an icon or enter a relative path';

	//Objetos, seguridad y otros
	$MULTILANG_ObjError='The type of object received in this command is unknown';
	$MULTILANG_SecErrorTit='Commands & reports security control';
	$MULTILANG_SecErrorDes='You have attempted to execute a function, command or report for which you are unauthorized.<br>System will be taking an audit log:';
	
	//Tablas
	$MULTILANG_TblError1='Design integrity problem';
	$MULTILANG_TblError2='DATABASE ERROR';
	$MULTILANG_TblError3='During the execution engine has returned the following message';
	$MULTILANG_TblAgrCampo='Add fields in the data table';
	$MULTILANG_TblAgrCampoTabla='Add a field to the table';
	$MULTILANG_TblEntero='Integer';
	$MULTILANG_TblCadena='String (Max length 255)';
	$MULTILANG_TblTexto='Text (Unlimited)';
	$MULTILANG_TblFecha='Date (without time)';
	$MULTILANG_TblTitNombre='Format help for field name';
	$MULTILANG_TblDesNombre='Field name without dashes, dots, spaces or special characters';
	$MULTILANG_TblLongitud='Length';
	$MULTILANG_TblAutoinc='Autoincrement';
	$MULTILANG_TblDesLongitud='This field may be mandatory depending on the type of data to be stored, such as type String fields';
	$MULTILANG_TblDesLongitud2='Format: If you ever need to put a backslash (backslash) or a single quote between these values​​, always place an additional backslash (backslash). For enum fields or set, use the format: \'a\',\'b\',\'c\'...';
	$MULTILANG_TblTitAutoinc='Primary key alert';
	$MULTILANG_TblDesAutoinc='This value can be defined only by advanced administrators who have been removed for some reason the default autoincrement ID field';
	$MULTILANG_TblNulos='Allow null value?';
	$MULTILANG_TblDefUsuario='User-defined';
	$MULTILANG_TblNulo='Null';
	$MULTILANG_TblFechaHora='Current date';
	$MULTILANG_TblDesPredet='Format: Only one value, unescaped. For strings use single quotation marks at the beginning and end';
	$MULTILANG_TblAgregando='Add the field';
	$MULTILANG_TblCamposDef='Fields already defined in the table';
	$MULTILANG_TblTipoClave='Key type';
	$MULTILANG_TblNoElim='Cant be eliminated';
	$MULTILANG_TblAdvDelCampo='IMPORTANT: Deleting the selected column of the table are also deleted all data stored in it then you can not undo this operation.\n'.$MULTILANG_Confirma;
	$MULTILANG_TblErrDel1='Error removing the table!';
	$MULTILANG_TblErrDel2='The specified table can not be deleted. Some common causes are: <br> <li> is used by any of the automated forms or reports, in that case you can try editing. <br> <li> The table has relationships defined by the designer to other data tables. <br> <li> user role defined for the active session can not delete objects in Practico';
	$MULTILANG_TblErrCrear='Please specify a valid name for the table. This must not contain dashes, dots, spaces or special characters';
	$MULTILANG_TblCrearListar='Create / List data tables defined in the system';
	$MULTILANG_TblCreaTabla='Create a new table in the database';
	$MULTILANG_TblDesTabla='A data table is a structure that allows you to store information. Enter in this field the name of the table without dashes, dots, spaces or special characters. CAPS SENSITIVE';
	$MULTILANG_TblCreaTabCampos='Create table and define fields';
	$MULTILANG_TblTitAsis='Use Wizard?';
	$MULTILANG_TblDesAsis='Lets you select from some predefined common tables';
	$MULTILANG_TblTablasBD='Tables defined in the database';
	$MULTILANG_TblRegistros='Records';
	$MULTILANG_TblAdvDelTabla='IMPORTANT: Deleting the data table are also deleted all the records stored in it then you can not undo this operation.\n'.$MULTILANG_Confirma;
	$MULTILANG_TblErrPlantilla='You must select a template from which you want to create your new table';
	$MULTILANG_TblAsistente='Table Generation Wizard';
	$MULTILANG_TblAsistNombre='Name for the new table';
	$MULTILANG_TblAsistPlant='Template selected';
	$MULTILANG_TblAsCampos='Fields containing';
	$MULTILANG_TblTotCampos='Total fields';
	$MULTILANG_TblHlpAsist='All tables and fields can be personalized in the next step, <br> adding, removing or changing the properties of those that you want.';
    $MULTILANG_TblTipoCopia1='Structure only (CREATE Sentence)';
    $MULTILANG_TblTipoCopia2='Data (INSERT Sentences)';
    $MULTILANG_TblTipoCopia3='Structure and Data (CREATE and INSERT sentences)';
    $MULTILANG_TblImportar='Import from file';
    $MULTILANG_TblImportarSQL='Upload a compressed SQL';
    $MULTILANG_TblSQLConsejo='If you execute the SQL sentences of this file you could be erasing, creating or overwritting tables and many other information, even designs and other things the you exported in that records. <br><br><b>We recomend you that make a backup before continue.</b>';
    $MULTILANG_TblEjecutarSQL='Run SQL sentences in this file (could take some time)';
    $MULTILANG_TblDecodificarActual='Collation or charset for the actual records or data table';
    $MULTILANG_TblCodificar='ENCODE records before save them to the backup file using';
    $MULTILANG_TblCodificacionNINGUNO='NONE, Use the original table collation or charset';
    $MULTILANG_TblTransliteracion='Use character transliteration';
    $MULTILANG_TblTransliteracionHlp='If transliteration is activated when a character cant be represented in the target charset, it can be approximated through one or several similarly looking characters. If you decide to ignore then invalid characters will be omited, Otherwise the string is truncated and, E_NOTICE is generated and the function will return FALSE.';
    $MULTILANG_TblTranslit='Translitering';
    $MULTILANG_TblIgnora='Ignoring';

	//Usuarios
	$MULTILANG_UsrCopia='Permissions copy completed. Please check below.';
	$MULTILANG_UsrDesPW='Passwords with minimum safety conditions should have a length of <b>at least 8 characters</b>, numbers, uppercase and lowercase symbols such as <font color=blue>$ * </font>. To have your password is considered safe by this system <b> must meet at least one security level of 81%</b>';
	$MULTILANG_UsrCambioPW='Change Password';
	$MULTILANG_UsrAnteriorPW='Old Password';
	$MULTILANG_UsrNuevoPW='New password';
	$MULTILANG_UsrNivelPW='Security level';
	$MULTILANG_UsrVerificaPW='Verify Password';
	$MULTILANG_UsrHlpNoPW='The authentication engine is defined for the external type tool.<br>
				The password change and user profile updates are disabled as it should be managed centrally for you in the tool defined by your system administrator';
	$MULTILANG_UsrErrPW1='You forgot to enter any of the requested data';
	$MULTILANG_UsrErrPW2='You have entered two different passwords';
	$MULTILANG_UsrErrPW3='The key for you entered does not meet the minimum safety recommendations';
	$MULTILANG_UsrErrInf='The user already has the selected permission';
	$MULTILANG_UsrAdmInf='User reports Administration';
	$MULTILANG_UsrAgreInf='Add a report to the user menu';
	$MULTILANG_UsrInfDisp='Available Reports';
	$MULTILANG_UsrAdvDel='IMPORTANT: Deleting the registry can be no link some system options for this user.\n'.$MULTILANG_Confirma;
	$MULTILANG_UsrAdmPer='User Rights Management';
	$MULTILANG_UsrCopiaPer='Initially make a permissions copy from the user';
	$MULTILANG_UsrDelPer='Only delete permissions';
	$MULTILANG_UsrAgreOpc='Add option to the user menu';
	$MULTILANG_UsrSecc='Sections already available';
	$MULTILANG_UsrErrCrea1='The user entered already exists, please check or change the login entered for the account and try again';
	$MULTILANG_UsrErrCrea2='You forgot to enter any of the requested data as required';
	$MULTILANG_UsrErrCrea3='The password entered must be at least six characters';
	$MULTILANG_UsrAdicion='Adding users';
	$MULTILANG_UsrLogin='NickName / Login';
	$MULTILANG_UsrDesLogin='Unique login to identify the user in the system. CAPS SENSITIVE';
	$MULTILANG_UsrNombre='Full name';
	$MULTILANG_UsrTitCorreo='Address for alerts and notifications';
	$MULTILANG_UsrDesCorreo='E-mail of possible use for automatic notifications system in some modules';
	$MULTILANG_UsrEstado='Initial state';
	$MULTILANG_UsrNivel='Access level';
	$MULTILANG_UsrInterno='Internal user?';
	$MULTILANG_UsrDesInterno='An internal user is for people who work inside the company that deploy the ERP or system.  An external user is for example for people that is from a customer or another company that login to the system';
	$MULTILANG_UsrTitNivel='Initial safety profile';
	$MULTILANG_UsrDesNivel='Users security profile. CAUTION: This option is different to individual user permissions defined by the designer for the created objects. This page only applies to the internal operations of Practico';
	$MULTILANG_UsrAudit1='Tracking operations (automatically updated every 5 seconds)';
	$MULTILANG_UsrAudDes='Details of the action';
	$MULTILANG_UsrAudUsrs='Monitoring transactions for all users';
	$MULTILANG_UsrAudAccion='With the ACTION';
	$MULTILANG_UsrAudUsuario='for the <b>user</b>';
	$MULTILANG_UsrAudDesde='From (Day / Month)';
	$MULTILANG_UsrAudHasta='to';
	$MULTILANG_UsrAudAno='Referring year audit';
	$MULTILANG_UsrAudIniReg='Start on record';
	$MULTILANG_UsrAudVisual='Viewing';
	$MULTILANG_UsrAudMonit='Monitoring mode';
	$MULTILANG_UsrAudHisto='History of user operations (from most recent to oldest)';
	$MULTILANG_UsrLista='List of users in the system';
	$MULTILANG_UsrLisNombre='See only users whose NAME contains';
	$MULTILANG_UsrLisLogin='See only users whose LOGIN contains';
	$MULTILANG_UsrFiltro='Due to the number of registered users you should filter the output.<br>
				Enter the desired filter type at the top and click the corresponding button.';
	$MULTILANG_UsrAcceso='Last access';
	$MULTILANG_UsrAdvSupr='IMPORTANT: You are going to delete the user and lose links to records associated with this, this action can not be recovered unless you recreate the user with the same credentials later.\n'.$MULTILANG_Confirma;
	$MULTILANG_UsrAddMenu='Add Menus';
	$MULTILANG_UsrAddInfo='Add Reports';
	$MULTILANG_UsrAuditoria='Audit';
	$MULTILANG_UsrAgregar='Add a User';
	$MULTILANG_UsrVerAudit='View user audit';
	$MULTILANG_UsrReset='पासवर्ड रीसेट';
    $MULTILANG_UsrOlvideClave='मैं अपना पासवर्ड भूल गया';
    $MULTILANG_UsrOlvideUsuario='मैं अपना उपयोगकर्ता नाम भूल गया';
    $MULTILANG_UsrIngreseUsuario='अपने उपयोगकर्ता नाम टाइप करें';
    $MULTILANG_UsrIngreseCorreo='पंजीकृत ईमेल लिखें';
    $MULTILANG_UsrResetAdmin='यदि आप एक पासवर्ड के बाद सिस्टम के लिए एक सफल उपयोग कर सकते है अगर तुम न आप के लिए अपना पासवर्ड रीसेट कर सकता है जो आपके सिस्टम प्रशासक को लिख सकते हैं बहाल।.';
    $MULTILANG_UsrAsuntoReset='पहुंच रीसेट';
    $MULTILANG_UsrMensajeReset='उपयोगकर्ता और चाबी बहाली के लिए जानकारी के साथ एक ईमेल भेजा गया था। निर्देश देखने के लिए आपके इनबॉक्स और स्पैम फोल्डर में अपने ईमेल की जांच करने के लिए याद रखें। व्यापार लिस्टिंग कोई लिंक अगले दिन में समाप्त हो जाएगी या उस लिंक succefully प्रयोग किया जाता है जब अपना पासवर्ड रीसेट करने के लिए। <HR> ईमेल के लिए subjet ऐसा कुछ हो जाएगा : <b>['.$NombreRAD.'] '.$MULTILANG_UsrAsuntoReset.'</b>';
    $MULTILANG_UsrErrorReset='पासवर्ड रीसेट करने की प्रक्रिया के लिए प्रवेश जानकारी अमान्य था, में प्रवेश किया नाम या ईमेल नहीं करता है प्रणाली में मौजूद है। डेटा की जाँच करें और पुन: प्रयास करें.';
    $MULTILANG_UsrResetLink='अपना पासवर्ड बहाल करने के लिए इस लिंक का पालन करें';
    $MULTILANG_UsrResetCuenta='संदेश भेजा';
    $MULTILANG_UsrResetOK='पासवर्ड बहाल। फिर से प्रवेश करने की कोशिश करें';
    $MULTILANG_UsrPerfil='उपयोगकर्ता प्रोफ़ाइल';
    $MULTILANG_UsrActualizarAdmin='आपकी सेटिंग्स आप व्यवस्थापक उपयोगकर्ता के लिए ईमेल पते अपडेट करने के लिए अपने प्रोफ़ाइल में परिवर्तन होना चाहिए कि कहते हैं। शब्दकोश सुपर उपयोगकर्ता या इसे बदलने के लिए उपयोगकर्ता नाम विकल्प पर ऊपरी उपयोगकर्ता मेनू और Clic के लिए जाओ।';
    $MULTILANG_UsrCreacionOK='खाता उपयोगकर्ता जोड़ा गया है। अब जरूरत है कि आप किसी भी मेनू विकल्प या रिपोर्ट में जोड़ने के लिए फ़िल्टर किया जाता है। इस पल में सही आवंटित करने के लिए आवश्यक नहीं है, तो आप इस कार्रवाई को रद्द कर सकता है.';
    $MULTILANG_UsrSaltarInformes='इस प्रयोक्ता के लिए अधिकारों की रिपोर्ट करने के लिए कूदो';
    $MULTILANG_UsrSaltarMenues='इस उपयोगकर्ता के लिए मेनू के अधिकार के लिए कूदो';


	//Proceso de instalacion
	$MULTILANG_Instalacion='Installation Process';
	$MULTILANG_SubtituloPractico1='WEB Application Generator';
	$MULTILANG_SubtituloPractico2='Free and cross-platform';
	$MULTILANG_InstaladorAplicacion='Application installer';
	$MULTILANG_BienvenidaInstalacion='Welcome to the installation process';
	$MULTILANG_BienvenidaDescripcion='This wizard will guide you every step of the initial configurations to use Practico as a visual environment for web application development';
	$MULTILANG_ResumenLicencia='This tool is released under GNU-GPL v2';
	$MULTILANG_AmpliacionLicencia='An online copy of this license can be found in different formats and languages ​​in the <a href="http://www.gnu.org/licenses/gpl-2.0.html">GNU website</a>';
	$MULTILANG_ChequeoPreprocesador='Checking preprocessor settings';
	$MULTILANG_VistaPreprocesador='A view of your PHP configuration is available in <b> <a target="_blank" href="paso_i.php">[this link]</a>';
	$MULTILANG_CumplirRequisitos='Must meet the following';
	$MULTILANG_CumplirPDO='PDO extension enabled';
	$MULTILANG_CumplirDrivers='PDO Driver for the type of engine of your target database';
	$MULTILANG_CumplirGD='GD Extension 2 + handling of graphics and support for FreeType 2 +';
	$MULTILANG_ChequeoDirectorios1='Checking directories';
	$MULTILANG_ChequeoDirectorios2='The following files and directories must have write permissions for the application to operate correctly';
	$MULTILANG_ErrorEscritura='<b> found errors when trying to write to the installation directories! </b>: <br> rule path must belong to the user running webserver Practical scripts (usually apache <br> www, www-data or similar) and have 755 permissions for folders and 644 case for. <br> A quick way to update these permissions can be run from the root of the Practical commands: <li> find. -type d-exec chmod 755 {} \; (change all folder permissions) <li> find. -type f-exec chmod 644 {} \; (change all file permissions) <li> chown-R www-data * (assuming that www-data is the user who runs the web service)';
	$MULTILANG_ProbarNuevamente='Test again';
	$MULTILANG_ConfiguracionDescripcion='Specify the desired settings to store user applications and information generated by Practical as well as other important options of the tool. This window will be presented only once so be sure to fill out and confirm all required information';
	$MULTILANG_PuertoNoPredeterminado='(if not the default)';
	$MULTILANG_AyudaTitMotor='MySQL and MariaDB';
	$MULTILANG_AyudaDesMotor='Engines are official. Above them is the development and testing of the tool, but thanks to PDO you can use the tool in other engines you may need to make adjustments to these specific operations.';
	$MULTILANG_AyudaTitBD='The database must already exist';
	$MULTILANG_AyudaDesBD='For different engines you must have created SQLite database first. For SQLite only required to specify the file name associated with BD (eg practico.sqlite3) and Practico will try to create for you the file if you have the appropriate permissions on your web server.';
	$MULTILANG_PrefijoCore='Pr&aacute;ctico internal tables prefix';
	$MULTILANG_PrefijoApp='Application tables prefix';
	$MULTILANG_AyudaTitPreCore='NO se recomienda dejar en blanco o Mayúsculas';
	$MULTILANG_AyudaDesPreCore='';
	$MULTILANG_AyudaTitPreApp='Important';
	$MULTILANG_AyudaDesPreApp='The prefix used for application tables can be used to separate different Practical facilities on the same database or it can be left empty to link / integrate with other applications Practical pre-existing. Not recommended uppercase for compatibility between engines.';
	$MULTILANG_AyudaLlave='Sign value for user accounts';
	$MULTILANG_NotasImportantesInst1=' <u>IMPORTANT 1 </u>: The database used for Practico must already exist to connect to it and generate the required structures. Check with your hosting provider or system administrator how to create a database with sufficient privilege to work with Practico. <br> <br> <u> IMPORTANT 2 </u>: The installer will remove all existing tables on database indicated and that match the names of tables that Practico uses. If you think you may have important information in them is recommended to make a backup before proceeding. To share a single database between different Practico installations you can change the table prefixes used by each.';
	$MULTILANG_ParametrosApp='Parameters for your application';
	$MULTILANG_ParamNombreEmpresaLargo='Full name of your organization or company';
	$MULTILANG_ParamNombreEmpresa='Short name of your organization or company';
	$MULTILANG_ParamFechaLanzamiento='Date of deployment';
	$MULTILANG_ParamNombreApp='Application name';
	$MULTILANG_ParamVersionApp='Initial release version of its application';
	$MULTILANG_AyudaTitNomEmp='Name to display on top';
	$MULTILANG_AyudaDesNomEmp='This text will be used in reports and application areas that require a name to identify your organization.';
	$MULTILANG_AyudaTitNomApp='Descriptive name';
	$MULTILANG_AyudaDesNomApp='The specified name always appears at the top of your application.';
	$MULTILANG_NotasImportantesInst2='<u>IMPORTANT</u>: Other parameters such as long and short name of your company, release date, license texts and credits will be able to be modified later in the options available for the administrator user.';
	$MULTILANG_AyudaTitCaptcha='Wordlength';
	$MULTILANG_AyudaDesCaptcha='Indicates the number of symbols used in the security word that users must enter to access the system each.';
	$MULTILANG_ModoDepuracion='Debug mode';
	$MULTILANG_AyudaTitDebug='Show errors and warnings';
	$MULTILANG_AyudaDesDebug='For production sites this option should be off. When you turn on this value, Practico will show you during application execution all errors and messages that can be generated by the Hypertext Preprocessor - PHP';
	$MULTILANG_MotorAuth='Authentication engine';
	$MULTILANG_AuthPractico='Internal (Practico Tables using MD5)';
	$MULTILANG_AuthLDAP='LDAP (Directory server)';
	$MULTILANG_AuthFederado='Federated (See config under application parameters)';
	$MULTILANG_AyudaDesAuth='Using a different authentication engine Practico not preclude the creation of users of the tool. The outboard motor will serve as a method to validate the login and corresponding password as a centralized authentication method, but the other features of the profile are taken from the Practico user. The Practico password change will be disabled to be controlled only by the external motor. The admin user will always remain autonomous to keep access control configuration errors.';
	$MULTILANG_AyudaTitCript='Key encryption type used by the engine';
	$MULTILANG_AyudaDesCript='Specify the type of encryption used by the authentication system to be used. Practico will encrypt the key value entered by the user before sending the verification engine.';
	$MULTILANG_AlgoritmoCripto='Encryption Algorithm';
	$MULTILANG_Dominio='Domain';
	$MULTILANG_UO='Organizational unit or context';
	$MULTILANG_AyudaDesLdapIP='Enter the server IP address or name directory where it can be resolved.';
	$MULTILANG_AyudaDesLdapDominio='Domain used by the server. Example: This will be created midominio.com.co internal chain dc=midominio,dc=com,dc=co';
	$MULTILANG_AyudaDesLdapUO='User Context Connection. Must exist on the LDAP server, eg people, sales, marketing, etc.';
	$MULTILANG_TitInsPaso3='Writing Configuration and connecting to Database';
	$MULTILANG_DesInsPaso3='I am writing configuracion.php file located in / core with the parameters you specified and is being tested Connects to the specified database.';
	$MULTILANG_ErrorEscribirConfig='<b>Found errors when trying to write the configuration file! </b>: <br> If you want an alternative may be to change your own default values ​​contained in the file core/configuracion.php or ws_llaves.php or core/ws_oauth.php depending of your desired changes.<br> <br> You can also change file permissions for configuracion.php and try again with this wizard.';
	$MULTILANG_ErrorConexBD='<b> found errors when connecting to the database! </b>: <br> Check the values ​​entered in the previous step and try again.';
	$MULTILANG_InfoPaso3='<b> Everything seems fine with the basic configuration of PDO. </b> <br> The last step is to tell the installation wizard like trying your database:<br><br>
				<li><b>1.</b> Add data start the database, this includes the initial user (admin), menus and other records on Practico Core tables. This is the best choice for new installations.
				<li><b>2.</b> Leave the database as it is, indicating that no operation is to be executed on the database. This option is useful when trying to install over an existing database that contains applications designed and active users. It can also be understood as a blank database for new installations will not even users to access and options to select.';
	$MULTILANG_BtnAplicarBD='1. Add initial info to the BD';
	$MULTILANG_BtnNoAplicarBD='2. Do not modify the BD connected';
	$MULTILANG_ExeScripts='Running database scripts (if applicable)';
	$MULTILANG_ErrorScripts='Error executing the query on the database';
	$MULTILANG_IrInstalacion='Go to your Practico installation';
	$MULTILANG_Totalejecutado='Total queries executed';
	$MULTILANG_MsjFinal1='If this is a new installation can enter the system through <b> credentials admin / admin </ b> and change then as you desire.';
	$MULTILANG_MsjFinal2='Remember to completely remove the installation directory (folder / ins) </b> </u> to prevent other person run these scripts again on a production system can cause any damage.';
	$MULTILANG_MsjFinal2='Summary of operations executed';
	$MULTILANG_AuthLDAPTitulo='LDAP based login';
	$MULTILANG_AuthOauthPlantilla='Template user';
	$MULTILANG_AuthOauthId='Client ID';
	$MULTILANG_AuthOauthSecret='Client Secret';
	$MULTILANG_AuthOauthURI='Redirect URI';
	$MULTILANG_OauthTitURI='Before you continue, you should register a new application with the provider to obtain an ID, Secret and URI to config the auth service.  The URI to register is calculated automatically by Practico in each URI field for this form.';
	$MULTILANG_OauthDesURI='Important: Your return URI should be under a domain or public IP because your provider will need to link with that. This URI is automatically created acording to the path during installation time.  Clic over each providers logo to go to their API registration website.';
	$MULTILANG_BuscarActual='Search for upgrades automatically';
	$MULTILANG_DescActual='Search randomly on admin logins to check for new Practicos versions.  This option could turn a little slower admin loads while checks for new versions';
	$MULTILANG_ConfGraficas='Change graphic configurations';

	//API-Webservices
	$MULTILANG_WSErrTitulo='Practico WebServices - Error';
	$MULTILANG_WSErr01='[Cod. 01] Invalid key';
	$MULTILANG_WSErr02='[Cod. 01] Secret value is not valid';
	$MULTILANG_WSErr03='[Cod. 03] WebServices functions file does not found';
	$MULTILANG_WSErr04='[Cod. 04] Webservice consumers key is empty or null. Check the value you sent or your Practico installation process.';
	$MULTILANG_WSErr05='[Cod. 05] The service identifier, function or method could not be executed, is uknown or is empty.';
	$MULTILANG_WSErr06='[Cod. 06] You dont have permission to run the service: ';
	$MULTILANG_WSErr07='[Cod. 07] API access unauthorized for the address: ';
	$MULTILANG_WSErr08='[Cod. 08] API access unauthorized for the domain: ';
	$MULTILANG_WSConfigButt='WebServices keys';
	$MULTILANG_WSLlavesDefinidas='<b>WebServices consumer Keys</b> (one each line)';
	$MULTILANG_WSLlavesAyuda='Those are the webservices keys that you allow to use Pr&aacute;ctico Webservices or user custom services.  It is not necessary to add your setup pass key cause it is allowed by default over all domains and functions';
	$MULTILANG_WSLlavesNuevo='Add a new API client';
	$MULTILANG_WSLlavesBorrar='You are going to delete the API keys selected.  Any application o foreign connection using that keys will be forbidden by Practico.  This operation can not be undo later, Are you sure?';
	$MULTILANG_WSLlavesNombre='Client name';
	$MULTILANG_WSLlavesLlave='Key';
	$MULTILANG_WSLlavesSecreto='Secret';
	$MULTILANG_WSLlavesURI='Redirect URI';
	$MULTILANG_WSLlavesDominio='Authorized domain(s)';
	$MULTILANG_WSLlavesIP='Authorized IP(s)';
	$MULTILANG_WSLlavesFunciones='Allowed services';
	$MULTILANG_WSLlavesAsterisco='(*) asterisk for any';


	//OAuth
	$MULTILANG_OauthButt='OAuth Autentication';
	$MULTILANG_ProtoTransporte='Prefered transport protocol';
	$MULTILANG_ProtoTransAUTO='Autodetect by URL';
	$MULTILANG_ProtoTransHTTP='HTTP standard';
	$MULTILANG_ProtoTransHTTPS='HTTP secured';
	$MULTILANG_ProtoDescripcion='Autodetect will check URLs used to access and will enable or disable SSL,  HTTP standard allow people with self-signed certs to connect with the Practicos auth webservice.  This is an unsafe mode but very effective if you need to access.   HTTP Secured requieres a valid SSL cert by a CA on your web server.';

	//Login Federado
	$MULTILANG_TitFederado='Federated Login';

	//Modulo de monitoreo
	$MULTILANG_MonTitulo='Monitoring system';
	$MULTILANG_MonPgInicio='Start page';
	$MULTILANG_MonConfig='Monitor configure';
	$MULTILANG_MonNuevo='Add a new monitor';
	$MULTILANG_MonCommShell='Shell command';
	$MULTILANG_MonCommSQL='SQL Query';
	$MULTILANG_MonDesTipo='This is the element that you want to add to the monitoring page';
	$MULTILANG_MonMetodo='Used method';
	$MULTILANG_MonSaltos='Line brakes';
	$MULTILANG_MonTamano='SQL font size';
	$MULTILANG_MonOcultaTit='Title hidding';
	$MULTILANG_MonCorreoAlerta='Alerts email';
	$MULTILANG_MonAlertaSnd='Soundest alert';
	$MULTILANG_MonMsLectura='Miliseconds for reading';
	$MULTILANG_MonDefinidos='Pages & Monitors defined';
	$MULTILANG_MonErr='Name field is mandatory';
	$MULTILANG_MonEstado='System status';
	$MULTILANG_MonAcerca='&copy; Monitoring system based on <a href="http://www.practico.org" style="color:#FFFFFF"><font color=white><b>Practico.org</b></font></a>';
	$MULTILANG_AplicaPara='This applies for: ';
	$MULTILANG_MonLinea='ON LINE';
	$MULTILANG_MonCaido='DOWN';

    //Modulo de correos
    $MULTILANG_MailIntro1='Automatic platform message';
    $MULTILANG_MailIntro2='Details about this message could be available in the system <span style="font-weight: bold;">'.$NombreRAD.'</span> using your user name and password.';
    $MULTILANG_MailIntro3='This message was delivered by an automatic system, please dont reply to it.';
    $MULTILANG_MailIntro4='Remember that our messages never ask you about personal information, security keys by email</span>, dont answer any message or fill any form that ask you about this kind of information out of our '.$NombreRAD.' system.';
    $MULTILANG_MailIntro5='All the information in this email and all its attachments is confidential for the bussiness and could be used for people who is related to it only. If you receive this message by error please delete it and tell sender about the error, any other operation with this email and its content will be under legal protection.';
    $MULTILANG_MailIntro6='<br><br>A system powered by <a href=http://www.practico.org>www.practico.org</a>';
