<?php return array(
    'root' => array(
        'name' => 'practico/framework',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '349f0e1244878bccdb79d2564a477e6a8a939ffa',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'd3js/d3js' => array(
            'pretty_version' => '7.6.1',
            'version' => '7.6.1.0',
            'reference' => 'tags/v7.6.1/',
            'type' => 'library',
            'install_path' => __DIR__ . '/../d3js/d3js',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jbdemonte/barcode' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => 'tags/php-barcode-2.0.3/',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jbdemonte/barcode',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jquery/jquery' => array(
            'pretty_version' => '3.6.1',
            'version' => '3.6.1.0',
            'reference' => NULL,
            'type' => 'jquery',
            'install_path' => __DIR__ . '/../jquery/jquery',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'practico/framework' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '349f0e1244878bccdb79d2564a477e6a8a939ffa',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
