<?php return array(
    'root' => array(
        'name' => 'practico/framework',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => 'ed85f302304680e6e80f47b3684ee3f2ffc1ed9f',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'components/jquery' => array(
            'pretty_version' => '3.6.0',
            'version' => '3.6.0.0',
            'reference' => '6cf38ee1fd04b6adf8e7dda161283aa35be818c3',
            'type' => 'component',
            'install_path' => __DIR__ . '/../components/jquery',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jbdemonte/barcode' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => 'tags/php-barcode-2.0.3/',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jbdemonte/barcode',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'practico/framework' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'ed85f302304680e6e80f47b3684ee3f2ffc1ed9f',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
