<?php
		$ServidorBD='127.0.0.1';
		$BaseDatos='practico';
		$UsuarioBD='root';
		$PasswordBD='';
		$MotorBD='mysql';
		$PuertoBD='';
		$NombreRAD='Pr&aacute;ctico';
		$PlantillaActiva='nomo';
		$ArchivoCORE='';
		$TablasCore='Core_';
		$TablasApp='App_';
		$LlaveDePaso='NA69PNHAT6';
		$ModoDepuracion=1;
		$ZonaHoraria='America/Bogota';
		$CaracteresCaptcha=1;
	?>
