<?php
		$ServidorBD='127.0.0.1';
		$BaseDatos='practico';
		$UsuarioBD='root';
		$PasswordBD='';
		$MotorBD='mysql';
		$PuertoBD='3306';
		$NombreRAD='Pr&aacute;ctico';
		$VersionRAD='12.05';
		$PlantillaActiva='nomo';
		$ArchivoCORE='';
		$TablasCore='Core_';
		$TablasApp='App_';
		$MotorTablasApp='MyISAM';
		$LlaveDePaso='';
	?>