<?php
		$ServidorBD='127.0.0.1';
		$BaseDatos='practico';
		$UsuarioBD='root';
		$PasswordBD='mypass';
		$MotorBD='mysql';
		$PuertoBD='';
		$NombreRAD='Pr&aacute;ctico';
		$PlantillaActiva='nomo';
		$ArchivoCORE='';
		$TablasCore='Core_';
		$TablasApp='App_';
		$LlaveDePaso='G4W7HVM9GC';
		$ModoDepuracion=0;
		$ZonaHoraria='America/Bogota';
		$CaracteresCaptcha=4;
		$Auth_TipoMotor='practico';
		$Auth_TipoEncripcion='plano';
		$Auth_LDAPServidor='127.0.0.1';
		$Auth_LDAPPuerto='389';
		$Auth_LDAPDominio='unixlandia.com';
		$Auth_LDAPOU='';
	?>
