<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite6fed76aa42f1bfc1713b12a98f515c4
{
    public static $files = array (
        'ad155f8f1cf0d418fe49e248db8c661b' => __DIR__ . '/..' . '/react/promise/src/functions_include.php',
    );

    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'React\\Promise\\' => 14,
        ),
        'G' => 
        array (
            'GuzzleHttp\\Stream\\' => 18,
            'GuzzleHttp\\Ring\\' => 16,
            'GuzzleHttp\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'React\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/promise/src',
        ),
        'GuzzleHttp\\Stream\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/streams/src',
        ),
        'GuzzleHttp\\Ring\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/ringphp/src',
        ),
        'GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'H' => 
        array (
            'Hitbtc' => 
            array (
                0 => __DIR__ . '/..' . '/hitbtc-com/hitbtc-php-sdk/src',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite6fed76aa42f1bfc1713b12a98f515c4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite6fed76aa42f1bfc1713b12a98f515c4::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInite6fed76aa42f1bfc1713b12a98f515c4::$prefixesPsr0;
            $loader->classMap = ComposerStaticInite6fed76aa42f1bfc1713b12a98f515c4::$classMap;

        }, null, ClassLoader::class);
    }
}
