<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Hitbtc' => array($vendorDir . '/hitbtc-com/hitbtc-php-sdk/src'),
);
